"use client";

import { animate } from "motion/react";

/**
 * Restores the INTERACTIVE CONTROLS the Framer runtime used to drive.
 *
 * `page-full.tsx` is generated by scripts/opsra_extract.py and must never be
 * hand-edited, so everything here attaches by querying the export's own
 * markers (`data-framer-name`, aria-label, component structure).
 *
 * Every number below was measured against the original export running WITH
 * its Framer runtime (opsra/index.html) and cross-checked against the Framer
 * component modules in opsra/js/*.mjs. See the constants for the citations.
 */

/* ------------------------------------------------------------------ *
 * Measured transitions (from opsra/js/*.mjs + Playwright measurement) *
 * ------------------------------------------------------------------ */

/** Faq Item component variant transition: `{bounce:0,delay:0,duration:.4,type:'spring'}` */
const FAQ_SPRING = { type: "spring", duration: 0.4, bounce: 0 } as const;

/** Slideshow `transitionControl`: `{type:'spring',stiffness:200,damping:40}` */
const SLIDESHOW_SPRING = {
  type: "spring",
  stiffness: 200,
  damping: 40,
  mass: 1,
} as const;

/** Slideshow arrow `whileTap` transition: `{duration:.15}` */
const ARROW_TAP_SECONDS = 0.15;

/** Slideshow `intervalControl` - measured 3017ms between autoplay steps. */
const SLIDESHOW_INTERVAL_MS = 3000;

/**
 * Number Counter code component (plugin id 84d4c1) defaults, as used here:
 *   duration = 2  -> per-digit tween runs `duration * 0.8` = 1.6s
 *   ease     = "easeInOut"
 *   stagger  = digitIndex * 0.1s
 *   trigger  = useInView(ref, { amount: 0.5 }), fires once
 */
const COUNTER_DURATION_S = 2 * 0.8;
const COUNTER_STAGGER_S = 0.1;
const COUNTER_EASE = "easeInOut" as const;
const COUNTER_IN_VIEW_AMOUNT = 0.5;

/**
 * Stat counter targets.
 *
 * The digits are NOT in the export's DOM - the Framer code component receives
 * `targetNumber` as a prop, so the transcription only kept the rendered "0"s.
 * These are the values the original animates to, matched by card label
 * position (the port's labels are a 1:1 rewrite of the original's).
 *
 *   original "Faster workflow execution"  -> 3.2x   -> "More content shipped"
 *   original "Reduction in manual tasks"  ->  80%   -> "Less manual production"
 *   original "Smarter decision making"    -> 4.6x   -> "Faster brief to first cut"
 *   original "Increase in team output"    ->  65%   -> "Of spend under a hard cap"
 */
const COUNTER_TARGETS: Record<string, string> = {
  "More content shipped": "32",
  "Less manual production": "80",
  "Faster brief to first cut": "46",
  "Of spend under a hard cap": "65",
};
/** Positional fallback, in the same DOM order as the four stat cards. */
const COUNTER_TARGETS_BY_INDEX = ["32", "80", "46", "65"];

/**
 * FAQ answers for the five items the transcription could not carry over.
 *
 * In Framer the FAQ list is ONE component holding `answer1..answer6` as props;
 * only the open item's paragraph is ever in the DOM, so the static export kept
 * exactly one answer. These five are written from claims already made
 * elsewhere on this page (pricing bullets, feature copy, comparison cards).
 *
 * TODO(content): this copy belongs in scripts/opsra_content.py so the
 * extractor can emit it into page-full.tsx; it lives here only because that
 * file is generated and out of this module's scope.
 */
const FAQ_FALLBACK_ANSWERS: Record<string, string> = {
  "Is marketer.sh worth it for a solo operator?":
    "Yes. The $5 starter pack is enough to run a niche for a week and see the whole pipeline end to end, and credits never expire. There is no subscription and no card on file, so you only ever spend what you have already put in.",
  "How does marketer.sh keep costs predictable?":
    "Every job shows a cost estimate before it runs, and per-niche and global daily spend caps stop work before it goes past your budget. A full audit trail records every dollar and every asset, so nothing is spent without a line item behind it.",
  "Can marketer.sh publish to the channels we already use?":
    "Yes. Connect your channels once and marketer.sh publishes to every connected channel from a single brief, so one written brief becomes video, ads, and SEO articles that go out on the schedule you set.",
  "How quickly can we get the first video out?":
    "Most teams are running in minutes. Write one brief, approve the plan, and the agents handle ideation, production, and QA while you review, so the first cut lands far sooner than a manual production cycle.",
  "What makes marketer.sh different from other AI tools?":
    "Most tools stop at generation. marketer.sh runs the whole pipeline - ideation, production, QA, scheduling, and publishing - with human approval gates before anything publishes or spends, and a hard cap on every dollar.",
};

/* ------------------------------------------------------------------ *
 * Helpers                                                             *
 * ------------------------------------------------------------------ */

type Disposer = () => void;

const REDUCED_MOTION_QUERY = "(prefers-reduced-motion: reduce)";

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia(REDUCED_MOTION_QUERY).matches
  );
}

let uid = 0;
function nextId(prefix: string): string {
  uid += 1;
  return `${prefix}-${uid}`;
}

function variantClass(el: Element): string | undefined {
  return Array.from(el.classList).find((c) => c.startsWith("framer-v-"));
}

function swapVariantClass(el: Element, from?: string, to?: string): void {
  if (from && from !== to) el.classList.remove(from);
  if (to) el.classList.add(to);
}

function isFocusable(el: Element): boolean {
  const node = el as HTMLElement;
  if (node.hasAttribute("disabled")) return false;
  if (node.getAttribute("aria-hidden") === "true") return false;
  if (node.tabIndex < 0) return false;
  const rect = node.getBoundingClientRect();
  return rect.width > 0 || rect.height > 0;
}

const FOCUSABLE_SELECTOR =
  'a[href], button, input, select, textarea, [tabindex]:not([tabindex="-1"])';

/* ------------------------------------------------------------------ *
 * 1. FAQ accordion                                                    *
 * ------------------------------------------------------------------ */

/**
 * The real collapsed state in the original is NOT `display:none` - the Framer
 * variant simply does not render the Paragraph node at all, and the item's
 * own `height:min-content` shrinks from 195px (open) to 88px (closed). The
 * open/closed variant classes also change padding (30px -> 24px 30px).
 *
 * Behaviour measured on the original:
 *   - exactly one item open at a time (radio-style)
 *   - clicking the OPEN item collapses it, so "all closed" is reachable
 *   - height animates with `{type:'spring',duration:.4,bounce:0}`, ~417ms
 *   - the paragraph never fades: opacity stays 1 throughout
 *   - the +/- icon swaps instantly (background-image swap, no tween)
 *   - Enter activates; Space does NOT in the original (we add it for a11y)
 */
function initAccordions(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  // An FAQ item is exactly "the element whose DIRECT child is a Faq Content
  // header row" - no hashed class names, no ancestor false positives.
  const allItems = Array.from(
    root.querySelectorAll<HTMLElement>(
      '[data-framer-name] > [data-framer-name="Faq Content"]',
    ),
  )
    .map((header) => header.parentElement)
    .filter((el): el is HTMLElement => el instanceof HTMLElement);

  // Group items by their shared list wrapper (desktop list vs mobile list).
  const groups = new Map<Element, HTMLElement[]>();
  for (const item of allItems) {
    const wrapper = item.parentElement?.parentElement;
    if (!wrapper) continue;
    const list = groups.get(wrapper);
    if (list) list.push(item);
    else groups.set(wrapper, [item]);
  }

  for (const [, items] of groups) {
    if (items.length < 2) continue;

    const openItem =
      items.find((i) => i.querySelector('[data-framer-name="Paragraph"]')) ??
      items[0];
    const closedItem = items.find((i) => i !== openItem);
    if (!closedItem) continue;

    const openName = openItem.getAttribute("data-framer-name") ?? "Open";
    const closedName = closedItem.getAttribute("data-framer-name") ?? "Close";
    const openVariant = variantClass(openItem);
    const closedVariant = variantClass(closedItem);

    const paragraphTemplate = openItem.querySelector<HTMLElement>(
      '[data-framer-name="Paragraph"]',
    );
    if (!paragraphTemplate) continue;

    // Icon variants: the open item shows "minus", the closed items "plus".
    const openIcon = openItem
      .querySelector('[data-framer-name="Icon Cover"]')
      ?.closest<HTMLElement>("[data-framer-name]:not([data-framer-name='Icon Cover'])");
    const closedIcon = closedItem
      .querySelector('[data-framer-name="Icon Cover"]')
      ?.closest<HTMLElement>("[data-framer-name]:not([data-framer-name='Icon Cover'])");
    const minus = openIcon
      ? {
          name: openIcon.getAttribute("data-framer-name") ?? "",
          variant: variantClass(openIcon),
          bg:
            openIcon.querySelector<HTMLElement>(
              '[data-framer-name="Icon Cover"]',
            )?.style.backgroundImage ?? "",
        }
      : null;
    const plus = closedIcon
      ? {
          name: closedIcon.getAttribute("data-framer-name") ?? "",
          variant: variantClass(closedIcon),
          bg:
            closedIcon.querySelector<HTMLElement>(
              '[data-framer-name="Icon Cover"]',
            )?.style.backgroundImage ?? "",
        }
      : null;

    type Entry = {
      item: HTMLElement;
      header: HTMLElement;
      panel: HTMLElement;
      heading: HTMLElement | null;
      createdPanel: boolean;
      originalTabIndex: string | null;
      initialName: string;
      initialVariant: string | undefined;
      open: boolean;
      /** Bumped on every toggle so a stale tween cannot land a stale state. */
      generation: number;
    };

    const entries: Entry[] = [];

    items.forEach((item) => {
      const header = item.querySelector<HTMLElement>(
        '[data-framer-name="Faq Content"]',
      );
      if (!header) return;
      const heading = item.querySelector<HTMLElement>(
        '[data-framer-name="Heading"]',
      );
      const question = heading?.textContent?.trim() ?? "";

      let panel = item.querySelector<HTMLElement>(
        '[data-framer-name="Paragraph"]',
      );
      let createdPanel = false;

      if (!panel) {
        // The original mounts this node only in the open variant. Recreate it
        // from the open item's own markup so the styling stays identical.
        const clone = paragraphTemplate.cloneNode(true) as HTMLElement;
        const p = clone.querySelector("p");
        const answer = FAQ_FALLBACK_ANSWERS[question];
        if (p && answer) p.textContent = answer;
        else if (p && !answer) p.textContent = "";
        item.appendChild(clone);
        panel = clone;
        createdPanel = true;
      }

      const panelId = nextId("faq-panel");
      panel.id = panelId;
      panel.setAttribute("role", "region");
      if (heading) {
        if (!heading.id) heading.id = nextId("faq-heading");
        panel.setAttribute("aria-labelledby", heading.id);
      }

      const originalTabIndex = item.getAttribute("tabindex");
      // Move the tab stop onto the header so the panel is not nested inside
      // the button, which is what a disclosure pattern requires.
      item.setAttribute("tabindex", "-1");
      header.setAttribute("role", "button");
      header.setAttribute("tabindex", "0");
      header.setAttribute("aria-controls", panelId);

      const open = item === openItem;
      entries.push({
        item,
        header,
        panel,
        heading,
        createdPanel,
        originalTabIndex,
        initialName: item.getAttribute("data-framer-name") ?? "",
        initialVariant: variantClass(item),
        open,
        generation: 0,
      });

      // Items whose answer we could not recover stay inert rather than
      // opening onto an empty panel.
      const hasAnswer = (panel.textContent ?? "").trim().length > 0;
      if (!hasAnswer) {
        header.setAttribute("aria-disabled", "true");
      }

      applyState(entries[entries.length - 1], open, /* animateIt */ false);
    });

    function applyState(entry: Entry, open: boolean, animateIt: boolean): void {
      const { item, header, panel } = entry;
      const reduce = prefersReducedMotion();

      item.setAttribute("data-framer-name", open ? openName : closedName);
      swapVariantClass(
        item,
        open ? closedVariant : openVariant,
        open ? openVariant : closedVariant,
      );
      header.setAttribute("aria-expanded", open ? "true" : "false");

      const icon = open ? minus : plus;
      const iconHost = item
        .querySelector('[data-framer-name="Icon Cover"]')
        ?.closest<HTMLElement>(
          "[data-framer-name]:not([data-framer-name='Icon Cover'])",
        );
      if (icon && iconHost) {
        const cover = iconHost.querySelector<HTMLElement>(
          '[data-framer-name="Icon Cover"]',
        );
        iconHost.setAttribute("data-framer-name", icon.name);
        swapVariantClass(
          iconHost,
          variantClass(iconHost),
          icon.variant,
        );
        if (cover && icon.bg) cover.style.backgroundImage = icon.bg;
      }

      if (!animateIt || reduce) {
        panel.hidden = !open;
        item.style.height = "";
        item.style.overflow = "";
        entry.open = open;
        return;
      }

      const from = item.offsetHeight;
      panel.hidden = !open;
      item.style.height = "auto";
      const to = item.offsetHeight;
      item.style.height = `${from}px`;
      item.style.overflow = "hidden";
      // Keep the collapsing panel visible (and out of the a11y tree) while
      // the height animates, then unmount it from the a11y tree for good.
      if (!open) {
        panel.hidden = false;
        panel.setAttribute("aria-hidden", "true");
      } else {
        panel.removeAttribute("aria-hidden");
      }

      entry.generation += 1;
      const generation = entry.generation;
      const controls = animate(
        item,
        { height: [`${from}px`, `${to}px`] },
        FAQ_SPRING,
      );
      controls.then(() => {
        if (entry.generation !== generation) return;
        item.style.height = "";
        item.style.overflow = "";
        panel.hidden = !open;
        panel.removeAttribute("aria-hidden");
      });
      disposers.push(() => controls.stop());
      entry.open = open;
    }

    const toggle = (entry: Entry) => {
      if (entry.header.getAttribute("aria-disabled") === "true") return;
      const willOpen = !entry.open;
      for (const other of entries) {
        if (other === entry) continue;
        if (other.open) applyState(other, false, true);
      }
      applyState(entry, willOpen, true);
    };

    for (const entry of entries) {
      entry.item.addEventListener(
        "click",
        (event) => {
          // Never swallow a real link inside the card.
          if ((event.target as Element | null)?.closest("a")) return;
          toggle(entry);
        },
        { signal },
      );
      entry.header.addEventListener(
        "keydown",
        (event) => {
          if (event.key === "Enter" || event.key === " " || event.key === "Spacebar") {
            event.preventDefault();
            toggle(entry);
          }
        },
        { signal },
      );
    }

    disposers.push(() => {
      for (const entry of entries) {
        const { item, header, panel, originalTabIndex, createdPanel } = entry;
        item.style.height = "";
        item.style.overflow = "";
        item.setAttribute("data-framer-name", entry.initialName);
        swapVariantClass(item, variantClass(item), entry.initialVariant);
        if (originalTabIndex === null) item.removeAttribute("tabindex");
        else item.setAttribute("tabindex", originalTabIndex);
        header.removeAttribute("role");
        header.removeAttribute("tabindex");
        header.removeAttribute("aria-controls");
        header.removeAttribute("aria-expanded");
        header.removeAttribute("aria-disabled");
        if (createdPanel) panel.remove();
        else {
          panel.hidden = false;
          panel.removeAttribute("role");
          panel.removeAttribute("aria-labelledby");
          panel.removeAttribute("aria-hidden");
        }
      }
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 2. Slideshow / carousel                                             *
 * ------------------------------------------------------------------ */

/**
 * `section.framer-slideshow` is Framer's Slideshow code component. It sits in
 * the Comparison section (two instances) - the brief called it the social
 * proof carousel, but the social proof block has no slideshow.
 *
 * The arrows ship `disabled`, `pointer-events:none` and `opacity:0` because
 * that is the component's PRE-MEASUREMENT state
 * (`disabled: !(isCanvas || isInitialized)`); the live runtime flips all of it
 * on as soon as it has measured the items. It also clones the six slots to
 * four copies (`nt = et * 4`) so the loop never runs dry - the static export
 * only kept one copy, so we rebuild the other three.
 *
 * Position is composed from two independent offsets so this module can run
 * alongside `ticker.tsx`, which owns the slideshow's 3s autoplay and writes
 * `transform` on the same `<ul>` every frame:
 *
 *   final position = translateX(autoplay, ticker.tsx) + marginLeft(arrows, here)
 *
 * If no external driver is detected we take the autoplay on ourselves too, so
 * this file is still self-sufficient.
 *
 * Two deliberate deviations from the original, both flagged in the report:
 *   - this instance sets `showMouseControls:false`, so the original leaves the
 *     arrows at `display:none` - invisible AND unreachable. We lay them out at
 *     `opacity:0` and fade them in on hover/focus, so the at-rest pixels are
 *     unchanged while the control is genuinely operable and focusable.
 *   - the original never disables the arrows at the ends, because the track is
 *     infinite. Neither do we.
 */
function initSlideshows(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  const slideshows = Array.from(
    root.querySelectorAll<HTMLElement>("section.framer-slideshow"),
  );

  for (const section of slideshows) {
    if (section.dataset.controlsSlideshow) continue;
    const track = section.querySelector<HTMLElement>("ul");
    const prev = section.querySelector<HTMLButtonElement>(
      'button[aria-label="Previous"]',
    );
    const next = section.querySelector<HTMLButtonElement>(
      'button[aria-label="Next"]',
    );
    if (!track) continue;

    const originals = Array.from(track.children) as HTMLElement[];
    const count = originals.length;
    if (count < 2) continue;

    // ticker.tsx stamps `will-change: transform` on the list it is driving.
    const externalAutoplay = track.style.willChange === "transform";
    section.dataset.controlsSlideshow = externalAutoplay ? "arrows" : "full";

    const trackId = nextId("slideshow-track");
    track.id = trackId;

    // --- rebuild the 4x looping track (matches `nt = et * 4` in the runtime)
    const COPIES = 4;
    const clones: HTMLElement[] = [];
    for (let copy = 1; copy < COPIES; copy += 1) {
      for (const li of originals) {
        const clone = li.cloneNode(true) as HTMLElement;
        clone.setAttribute("aria-hidden", "true");
        clone
          .querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)
          .forEach((el) => el.setAttribute("tabindex", "-1"));
        clones.push(clone);
        track.appendChild(clone);
      }
    }

    const gap = Number.parseFloat(getComputedStyle(track).gap || "0") || 0;
    const measure = () => {
      const first = originals[0]?.firstElementChild as HTMLElement | null;
      return (first?.getBoundingClientRect().width ?? 0) + gap;
    };

    let step = measure();
    let total = step * count;
    // The page module passes `startFrom: 1`, and the export's SSR transform
    // (`translateX(calc(-1 * (100% + 11px)))`) already parks the track one
    // slot in, so our own offset starts at 0 on slide index 1.
    const START_INDEX = 1;
    let index = START_INDEX;

    /** Our own offset only ever spans one loop length: (-total, 0]. */
    const wrap = (value: number) => {
      if (total <= 0) return 0;
      return -((((-value % total) + total) % total));
    };

    const previousMargin = track.style.marginLeft;
    let offset = 0;
    const paint = (value: number) => {
      offset = value;
      track.style.marginLeft = `${value.toFixed(2)}px`;
    };
    paint(0);

    // Static, accurate button names; a polite live region carries the position
    // so a focused button's accessible name never changes under the user.
    section.setAttribute("aria-roledescription", "carousel");
    const status = document.createElement("span");
    status.setAttribute("aria-live", "polite");
    status.style.cssText =
      "position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0";
    section.appendChild(status);
    disposers.push(() => status.remove());

    const announce = () => {
      const position = ((index % count) + count) % count;
      const label = originals[position]?.textContent?.trim() ?? "";
      status.textContent = `Slide ${position + 1} of ${count}${label ? `: ${label}` : ""}`;
    };

    let current: ReturnType<typeof animate> | null = null;

    const goTo = (delta: number) => {
      index += delta;
      const settled = wrap(-(index - START_INDEX) * step);
      const from = offset;
      // Unwrap the target so the tween always travels the asked direction.
      let to = settled;
      if (delta > 0) while (to >= from) to -= total;
      else while (to <= from) to += total;

      current?.stop();
      current = null;

      if (prefersReducedMotion()) {
        paint(settled);
        announce();
        return;
      }

      current = animate(from, to, {
        ...SLIDESHOW_SPRING,
        onUpdate: (v: number) => {
          offset = v;
          track.style.marginLeft = `${v.toFixed(2)}px`;
        },
        onComplete: () => paint(settled),
      });
      announce();
    };

    // --- enable the arrows: exactly what the runtime does once measured
    const arrowWrapper = prev?.parentElement as HTMLElement | null;
    const restoreArrow: Disposer[] = [];
    for (const button of [prev, next]) {
      if (!button) continue;
      const before = {
        disabled: button.disabled,
        pointerEvents: button.style.pointerEvents,
        cursor: button.style.cursor,
        display: button.style.display,
        opacity: button.style.opacity,
        transition: button.style.transition,
      };
      button.disabled = false;
      button.removeAttribute("disabled");
      button.style.pointerEvents = "auto";
      button.style.cursor = "pointer";
      button.style.display = "block";
      button.style.opacity = "0";
      button.style.transition = `opacity ${ARROW_TAP_SECONDS}s ease-out, transform ${ARROW_TAP_SECONDS}s ease-out`;
      button.setAttribute("aria-controls", trackId);
      restoreArrow.push(() => {
        button.disabled = before.disabled;
        if (before.disabled) button.setAttribute("disabled", "");
        button.style.pointerEvents = before.pointerEvents;
        button.style.cursor = before.cursor;
        button.style.display = before.display;
        button.style.opacity = before.opacity;
        button.style.transition = before.transition;
        button.removeAttribute("aria-controls");
      });
    }
    if (arrowWrapper) {
      const beforeOpacity = arrowWrapper.style.opacity;
      arrowWrapper.style.opacity = "1";
      restoreArrow.push(() => {
        arrowWrapper.style.opacity = beforeOpacity;
      });
    }
    disposers.push(() => {
      for (const restore of restoreArrow) {
        try {
          restore();
        } catch {
          /* keep restoring the rest */
        }
      }
    });
    announce();

    const setArrowsVisible = (visible: boolean) => {
      for (const button of [prev, next]) {
        if (button) button.style.opacity = visible ? "1" : "0";
      }
    };
    section.addEventListener("pointerenter", () => setArrowsVisible(true), {
      signal,
    });
    section.addEventListener("pointerleave", () => setArrowsVisible(false), {
      signal,
    });
    section.addEventListener("focusin", () => setArrowsVisible(true), {
      signal,
    });
    section.addEventListener(
      "focusout",
      (event) => {
        if (!section.contains(event.relatedTarget as Node | null)) {
          setArrowsVisible(false);
        }
      },
      { signal },
    );

    /** The component's own arrow feedback: `whileTap {scale:.9}`, 0.15s. */
    const tapFeedback = (button: HTMLButtonElement) => {
      if (prefersReducedMotion()) return;
      button.style.transform = "scale(0.9)";
      window.setTimeout(() => {
        button.style.transform = "none";
      }, ARROW_TAP_SECONDS * 1000);
    };

    // --- autoplay: 3s per step while in view (`playOffscreen: false`).
    // Skipped when ticker.tsx is already running it on this element.
    let timer: number | undefined;
    let inView = false;

    const stopAutoplay = () => {
      if (timer !== undefined) window.clearTimeout(timer);
      timer = undefined;
    };
    const tick = () => {
      timer = window.setTimeout(() => {
        goTo(1);
        tick();
      }, SLIDESHOW_INTERVAL_MS);
    };
    const restartAutoplay = () => {
      stopAutoplay();
      if (externalAutoplay) return;
      if (inView && !prefersReducedMotion()) tick();
    };

    prev?.addEventListener(
      "click",
      () => {
        tapFeedback(prev);
        goTo(-1);
        restartAutoplay();
      },
      { signal },
    );
    next?.addEventListener(
      "click",
      () => {
        tapFeedback(next);
        goTo(1);
        restartAutoplay();
      },
      { signal },
    );

    const io = new IntersectionObserver(
      (entries) => {
        inView = entries.some((e) => e.isIntersecting);
        restartAutoplay();
      },
      { threshold: 0 },
    );
    io.observe(section);

    const onResize = () => {
      const resized = measure();
      if (!resized || Math.abs(resized - step) < 0.5) return;
      step = resized;
      total = step * count;
      paint(wrap(-(index - START_INDEX) * step));
    };
    window.addEventListener("resize", onResize, { signal });

    const mq = window.matchMedia(REDUCED_MOTION_QUERY);
    const onMq = () => restartAutoplay();
    mq.addEventListener("change", onMq);

    disposers.push(() => {
      // Cleared first: a stranded guard flag would make the next mount skip
      // rebuilding the 4x track (React StrictMode remounts this effect).
      delete section.dataset.controlsSlideshow;
      stopAutoplay();
      current?.stop();
      io.disconnect();
      mq.removeEventListener("change", onMq);
      clones.forEach((c) => c.remove());
      track.style.marginLeft = previousMargin;
      track.removeAttribute("id");
      section.removeAttribute("aria-roledescription");
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 3. Stat counters                                                    *
 * ------------------------------------------------------------------ */

/**
 * The Number Counter code component renders one "digit slot" per digit
 * (`min-width:0.6em`, `overflow:hidden`) holding an absolutely positioned
 * digit at `translateY(0%)`. It animates a float per slot and paints
 * `floor(v)` plus the next digit offset by the fraction, i.e. an odometer.
 */
function initCounters(root: HTMLElement): Disposer {
  const disposers: Disposer[] = [];

  const containers = Array.from(
    root.querySelectorAll<HTMLElement>('[data-code-component-plugin-id="84d4c1"]'),
  );
  if (!containers.length) return () => {};

  // Label -> target, with a positional fallback keyed on visual order.
  const labelFor = (container: HTMLElement): string => {
    const card = container.closest<HTMLElement>('[data-framer-name="Numbers and Icon"]')
      ?.parentElement;
    if (!card) return "";
    const clone = card.cloneNode(true) as HTMLElement;
    clone
      .querySelectorAll('[data-code-component-plugin-id="84d4c1"]')
      .forEach((n) => n.remove());
    return (clone.textContent ?? "").trim();
  };

  let ordinal = 0;
  const seenLabels = new Map<string, number>();

  for (const container of containers) {
    const slots = Array.from(
      container.querySelectorAll<HTMLElement>('div[style*="0.6em"]'),
    ).filter((el) => el.firstElementChild);
    if (!slots.length) continue;

    const label = labelFor(container);
    let target = COUNTER_TARGETS[label];
    if (!target) {
      // Fall back to position: containers repeat once per breakpoint variant.
      let bucket = seenLabels.get(label);
      if (bucket === undefined) {
        bucket = ordinal % COUNTER_TARGETS_BY_INDEX.length;
        seenLabels.set(label, bucket);
        ordinal += 1;
      }
      target = COUNTER_TARGETS_BY_INDEX[bucket];
    }

    const digits = target
      .split("")
      .filter((c) => c >= "0" && c <= "9")
      .map((c) => Number.parseInt(c, 10));
    if (!digits.length) continue;

    const paint = (slotIndex: number, value: number) => {
      const slot = slots[slotIndex];
      if (!slot) return;
      const base = slot.firstElementChild as HTMLElement | null;
      if (!base) return;
      const whole = Math.floor(value);
      const frac = value - whole;
      base.textContent = String(Math.max(0, Math.min(9, whole)));
      base.style.transform = `translateY(${(frac * -100).toFixed(3)}%)`;

      const upcoming = whole + 1;
      let follower = slot.children[1] as HTMLElement | undefined;
      if (frac > 0 && upcoming <= 9) {
        if (!follower) {
          follower = base.cloneNode(false) as HTMLElement;
          follower.setAttribute("aria-hidden", "true");
          slot.appendChild(follower);
        }
        follower.textContent = String(upcoming);
        follower.style.transform = `translateY(${((1 - frac) * 100).toFixed(3)}%)`;
      } else if (follower) {
        follower.remove();
      }
    };

    const settle = () => {
      digits.forEach((d, i) => {
        const slot = slots[i];
        if (!slot) return;
        const extra = slot.children[1];
        if (extra) extra.remove();
        const base = slot.firstElementChild as HTMLElement | null;
        if (!base) return;
        base.textContent = String(d);
        base.style.transform = "translateY(0%)";
      });
    };

    let started = false;
    const run = () => {
      if (started) return;
      started = true;

      if (prefersReducedMotion()) {
        settle();
        return;
      }

      digits.forEach((to, i) => {
        const controls = animate(0, to, {
          duration: COUNTER_DURATION_S,
          ease: COUNTER_EASE,
          delay: i * COUNTER_STAGGER_S,
          onUpdate: (v: number) => paint(i, v),
          onComplete: () => paint(i, to),
        });
        disposers.push(() => controls.stop());
      });
    };

    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          run();
          io.disconnect();
        }
      },
      { threshold: COUNTER_IN_VIEW_AMOUNT },
    );
    io.observe(container);
    disposers.push(() => io.disconnect());
    disposers.push(() => {
      slots.forEach((slot) => {
        const extra = slot.children[1];
        if (extra) extra.remove();
        const base = slot.firstElementChild as HTMLElement | null;
        if (base) {
          base.textContent = "0";
          base.style.transform = "translateY(0%)";
        }
      });
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 4. Mobile / tablet nav menu                                         *
 * ------------------------------------------------------------------ */

/**
 * The Nav component has five variants; the hamburger ("Menu Icon", variants
 * Closed / Open State) flips the nav from Phone -> Phone Open or
 * Tablet -> Tab Open, which is the only condition under which the
 * `.framer-bwjtjp` Menu panel is rendered at all.
 *
 * DELIBERATE DEVIATION FROM THE ORIGINAL (product decision, not a port bug):
 * the original opens a 220x360 dropdown pinned under the hamburger, with no
 * enter or exit animation at all (Framer's variant root is `initial:false`).
 * This module replaces that presentation with a full-screen menu that wipes
 * open and wipes closed. Everything else the original did - variant/icon swap,
 * link labels + hrefs and the CTA cloned live out of the Desktop nav, close on
 * link tap - is preserved, and nothing about the nav bar itself changes.
 *
 * Motion, all of it borrowed from values already extracted elsewhere in this
 * folder rather than invented here (see MENU_SPRING_IN / _OUT below):
 *
 *   ground   clip-path wipe from the nav's lower edge, spring bounce 0, 0.6s
 *   links    opacity .001 -> 1, y 10 -> 0, spring bounce 0 0.6s, 75ms apart
 *   exit     the same wipe in reverse plus a flat fade, spring bounce 0, 0.4s
 *
 * The panel is appended to `document.body`, not to the nav: it must be
 * impossible for an ancestor's `overflow` or stacking context to clip a
 * viewport-sized element. The nav's own fixed container is lifted above it
 * while open so the logo and the X stay visible and tappable.
 */
const NAV_OPEN_VARIANTS: Record<string, { cls: string; name: string }> = {
  // Phone -> Phone Open
  "framer-v-1bdgyp0": { cls: "framer-v-1neiqul", name: "Phone Open" },
  // Tablet -> Tab Open
  "framer-v-l1gk15": { cls: "framer-v-1t1qv3v", name: "Tab Open" },
};

const HAMBURGER_OPEN_CLASS = "framer-v-jcqq8b";

/** The "Open State" X glyph, lifted verbatim from the running original. */
const HAMBURGER_OPEN_ICON =
  'url("data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 22 22%22><path d=%22M 5.123 5.35 C 5.389 5.083 5.821 5.083 6.087 5.35 L 10.795 10.057 L 9.831 11.021 L 5.123 6.314 C 4.857 6.047 4.857 5.616 5.123 5.35 Z M 16.694 15.956 C 16.96 16.222 16.96 16.654 16.694 16.92 C 16.428 17.187 15.996 17.187 15.73 16.92 L 10.795 11.986 L 11.759 11.021 Z M 6.087 16.693 L 10.795 11.986 L 9.831 11.021 L 5.123 15.729 C 4.857 15.995 4.857 16.427 5.123 16.693 C 5.389 16.959 5.821 16.959 6.087 16.693 Z M 16.694 6.086 C 16.96 5.82 16.96 5.389 16.694 5.122 C 16.428 4.856 15.996 4.856 15.73 5.122 L 10.795 10.057 L 11.759 11.021 Z%22 fill=%22rgb(255,255,255)%22></path></svg>")';

/* --- motion -------------------------------------------------------- *
 *
 * Nothing here is a new curve. The site knows exactly two bounce-0 spring
 * speeds and one stagger, all extracted from the original:
 *
 *   0.6s  the split-text reveal (`reveal.tsx` TEXT_TRANSITION) - "content
 *         arriving", used here for the ground wipe and the link entrance
 *   0.4s  the Faq Item variant transition (FAQ_SPRING, above) - the site's
 *         speed for a UI control changing state, used here for the exit
 *   75ms  the split-text per-line stagger (`reveal.tsx` TEXT_LINE_STAGGER)
 *   100ms the offset between a heading's reveal and the block under it
 *         (`reveal.tsx` SPRING_DELAY_200 vs SPRING_DELAY_300), used as the
 *         lead the ground gets over the first link
 */
const MENU_SPRING_IN = { type: "spring", bounce: 0, duration: 0.6 } as const;
const MENU_SPRING_OUT = { type: "spring", bounce: 0, duration: 0.4 } as const;
const MENU_ITEM_STAGGER = 0.075;
const MENU_CONTENT_DELAY = 0.1;
/** Split-text enter values, verbatim: `{effect: {opacity: .001, y: 10}}`. */
const MENU_ITEM_FROM_Y = 10;
const MENU_ITEM_FROM_OPACITY = 0.001;

/* --- design -------------------------------------------------------- *
 *
 * Colours are the export's own tokens:
 *   rgb(21, 30, 29)    #151E1D  page ground (nav background token)
 *   rgb(15, 21, 20)    #0F1514  card surface
 *   rgb(42, 60, 58)    borders  (token-6f736482…)
 *   var(--brand-primary)  brand accent (was a teal literal; the
 *                         overlay renders outside #main, where
 *                         bridge.css's token override cannot reach)
 *   rgb(129, 152, 149) muted text (token-8d29ccb4…)
 *   rgb(252, 253, 253) foreground (token-d51e9d36…)
 * Type is the nav's own: JetBrains Mono 500, uppercase, tight tracking.
 */
const MENU_STYLE_ID = "site-menu-style";

const MENU_CSS = `
.site-menu{position:fixed;top:0;left:0;right:0;height:100vh;height:100dvh;
  z-index:2147483000;display:flex;flex-direction:column;box-sizing:border-box;
  background-color:rgba(21,30,29,.97);
  background-image:radial-gradient(120% 55% at 50% 118%,color-mix(in srgb, var(--brand-primary, #41fff3) 13%, transparent),color-mix(in srgb, var(--brand-primary, #41fff3) 0%, transparent) 68%);
  -webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px);
  overflow:hidden;will-change:clip-path,opacity;-webkit-tap-highlight-color:transparent}
.site-menu__scroll{flex:1 1 auto;display:flex;flex-direction:column;
  overflow-y:auto;overscroll-behavior:contain;
  padding-top:calc(var(--site-menu-top,92px) + 22px);
  padding-bottom:calc(36px + env(safe-area-inset-bottom,0px))}
.site-menu__sheet{width:100%;max-width:640px;margin:0 auto;padding:0 16px;box-sizing:border-box}
.site-menu__title{display:flex;align-items:center;gap:12px;margin:0 0 16px;
  font-family:"JetBrains Mono",ui-monospace,monospace;font-size:12px;font-weight:500;
  line-height:1;letter-spacing:.12em;text-transform:uppercase;color:rgb(129,152,149)}
.site-menu__title::before{content:"";flex:none;width:6px;height:6px;border-radius:1px;
  background:var(--brand-primary, #41fff3);box-shadow:0 0 12px color-mix(in srgb, var(--brand-primary, #41fff3) 55%, transparent)}
.site-menu__title::after{content:"";flex:1 1 auto;height:1px;background:rgb(42,60,58)}
.site-menu__list{list-style:none;margin:0;padding:0;border-top:1px solid rgb(42,60,58)}
.site-menu__item{border-bottom:1px solid rgb(42,60,58)}
.site-menu__link{display:flex;align-items:center;gap:14px;padding:17px 2px;
  text-decoration:none;font-family:"JetBrains Mono",ui-monospace,monospace;font-size:20px;
  font-weight:500;line-height:1.15;letter-spacing:-.02em;text-transform:uppercase;
  color:rgb(252,253,253);transition:color .18s ease-out}
.site-menu__index{flex:none;min-width:24px;font-size:11px;letter-spacing:.06em;
  color:var(--brand-primary, #41fff3);opacity:.7}
.site-menu__label{flex:1 1 auto}
.site-menu__arrow{flex:none;font-size:15px;color:rgb(129,152,149);opacity:0;
  transform:translateX(-4px);transition:opacity .18s ease-out,transform .18s ease-out,color .18s ease-out}
.site-menu__link:hover,.site-menu__link:focus-visible{color:var(--brand-primary, #41fff3)}
.site-menu__link:hover .site-menu__arrow,
.site-menu__link:focus-visible .site-menu__arrow{opacity:1;transform:translateX(0);color:var(--brand-primary, #41fff3)}
.site-menu__link:focus-visible{outline:1px solid var(--brand-primary, #41fff3);outline-offset:2px}
.site-menu__cta{margin-top:26px}
.site-menu__cta>a{display:flex!important;width:100%!important;box-sizing:border-box}
.site-menu__cta>a>div{flex:1 0 auto!important;width:auto!important;justify-content:center}
@media (min-width:810px){
  .site-menu__sheet{max-width:720px;padding:0 46px}
  .site-menu__title{font-size:13px;margin-bottom:22px}
  .site-menu__link{font-size:30px;padding:24px 2px;gap:20px}
  .site-menu__index{font-size:12px;min-width:34px}
  .site-menu__cta{margin-top:34px}
}
@media (prefers-reduced-motion: reduce){.site-menu *{transition:none!important}}
`;

/** Installed once per document, removed when the last nav is torn down. */
function ensureMenuStyles(): Disposer {
  let style = document.getElementById(MENU_STYLE_ID);
  if (!style) {
    style = document.createElement("style");
    style.id = MENU_STYLE_ID;
    style.textContent = MENU_CSS;
    document.head.appendChild(style);
  }
  return () => style?.remove();
}

/* --- scroll lock ---------------------------------------------------- *
 *
 * `overflow:hidden` on <html> alone does not hold on iOS, so the panel takes
 * the page out of flow and pins it at its current offset. The saved offset is
 * mirrored onto a data attribute so a mount that finds a stranded lock (a hot
 * reload, a crashed teardown) can still undo it.
 */
type BodyStyleSnapshot = Record<string, string>;
const LOCKED_PROPS = [
  "position",
  "top",
  "left",
  "right",
  "width",
  "overflow",
  "paddingRight",
] as const;

let scrollSnapshot: BodyStyleSnapshot | null = null;
let scrollOffset = 0;

function lockBodyScroll(): void {
  if (scrollSnapshot) return;
  const body = document.body;
  const snapshot: BodyStyleSnapshot = {};
  for (const prop of LOCKED_PROPS) snapshot[prop] = body.style[prop];
  scrollSnapshot = snapshot;
  scrollOffset = window.scrollY;

  // Compensate for the scrollbar the lock removes, so nothing reflows.
  const gutter = window.innerWidth - document.documentElement.clientWidth;
  body.style.position = "fixed";
  body.style.top = `${-scrollOffset}px`;
  body.style.left = "0";
  body.style.right = "0";
  body.style.width = "100%";
  body.style.overflow = "hidden";
  if (gutter > 0) body.style.paddingRight = `${gutter}px`;
  body.dataset.siteMenuScrollLock = String(scrollOffset);
}

function unlockBodyScroll(): void {
  const body = document.body;
  const stranded = body.dataset.siteMenuScrollLock;
  if (!scrollSnapshot && stranded === undefined) return;
  const offset = scrollSnapshot ? scrollOffset : Number(stranded) || 0;
  for (const prop of LOCKED_PROPS) body.style[prop] = scrollSnapshot?.[prop] ?? "";
  delete body.dataset.siteMenuScrollLock;
  scrollSnapshot = null;
  window.scrollTo(0, offset);
}

/* --- panel ---------------------------------------------------------- */

type MenuOverlay = {
  overlay: HTMLElement;
  sheet: HTMLElement;
  /** Rows that carry the staggered entrance, in visual order. */
  stagger: HTMLElement[];
};

/**
 * Labels, hrefs and the CTA are cloned out of the live Desktop nav on every
 * open, so whatever the routes are at that moment is what the menu links to -
 * nothing about the destinations is hard-coded here.
 */
function buildMenuOverlay(root: HTMLElement, panelId: string): MenuOverlay | null {
  const source = Array.from(root.querySelectorAll<HTMLElement>("nav")).find(
    (n) => n.querySelector('[data-framer-name="Nav Links Wrap"]'),
  );
  if (!source) return null;

  const links = Array.from(
    source.querySelectorAll<HTMLElement>(
      '[data-framer-name="Nav Links Wrap"] [data-framer-name="Text Button"]',
    ),
  );
  const cta = source.querySelector<HTMLElement>(
    '[data-framer-name="Primary Button"]',
  );

  const titleId = `${panelId}-title`;

  const overlay = document.createElement("div");
  overlay.className = "site-menu";
  overlay.id = panelId;
  overlay.setAttribute("data-framer-name", "Menu");
  overlay.setAttribute("role", "dialog");
  overlay.setAttribute("aria-modal", "true");
  overlay.setAttribute("aria-labelledby", titleId);

  const scroll = document.createElement("div");
  scroll.className = "site-menu__scroll";

  const sheet = document.createElement("div");
  sheet.className = "site-menu__sheet";

  const title = document.createElement("h2");
  title.className = "site-menu__title";
  title.id = titleId;
  title.textContent = "Menu";
  sheet.appendChild(title);

  const stagger: HTMLElement[] = [];

  const list = document.createElement("ul");
  list.className = "site-menu__list";

  links.forEach((link, i) => {
    const anchor = link.querySelector("a");
    const href = anchor?.getAttribute("href");
    const label = (anchor?.textContent ?? link.textContent ?? "").trim();
    if (!label) return;

    const item = document.createElement("li");
    item.className = "site-menu__item";

    const a = document.createElement("a");
    a.className = "site-menu__link";
    if (href) a.setAttribute("href", href);
    for (const attr of ["target", "rel", "download"]) {
      const value = anchor?.getAttribute(attr);
      if (value) a.setAttribute(attr, value);
    }

    const index = document.createElement("span");
    index.className = "site-menu__index";
    index.setAttribute("aria-hidden", "true");
    index.textContent = String(i + 1).padStart(2, "0");

    const text = document.createElement("span");
    text.className = "site-menu__label";
    text.textContent = label;

    const arrow = document.createElement("span");
    arrow.className = "site-menu__arrow";
    arrow.setAttribute("aria-hidden", "true");
    arrow.textContent = "→";

    a.append(index, text, arrow);
    item.appendChild(a);
    list.appendChild(item);
    stagger.push(item);
  });

  sheet.appendChild(list);

  if (cta) {
    const ctaWrap = document.createElement("div");
    ctaWrap.className = "site-menu__cta";
    const clone = cta.cloneNode(true) as HTMLElement;
    clone.removeAttribute("id");
    ctaWrap.appendChild(clone);
    sheet.appendChild(ctaWrap);
    stagger.push(ctaWrap);
  }

  scroll.appendChild(sheet);
  overlay.appendChild(scroll);

  return { overlay, sheet, stagger };
}

/** The wipe: 0 = fully closed (clipped to the top edge), 1 = fully open. */
function paintWipe(overlay: HTMLElement, progress: number): void {
  const hidden = Math.max(0, Math.min(1, 1 - progress)) * 100;
  overlay.style.clipPath = `inset(0% 0% ${hidden.toFixed(2)}% 0%)`;
  // A short fade under the wipe softens the leading edge without washing the
  // panel out: opaque by the time the wipe is a third of the way down.
  overlay.style.opacity = Math.max(0, Math.min(1, progress * 3)).toFixed(3);
}

function initNavMenus(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  const navs = Array.from(root.querySelectorAll<HTMLElement>("nav")).filter(
    (nav) => nav.querySelector(".framer-TYMUs"),
  );
  if (!navs.length) return () => {};

  // A previous mount that could not finish its teardown (hot reload, an
  // exception mid-cleanup) would otherwise leave a panel and a scroll lock
  // behind, and the next mount would stack a second panel on top of it.
  document.querySelectorAll(".site-menu").forEach((stale) => stale.remove());
  unlockBodyScroll();

  disposers.push(ensureMenuStyles());

  for (const nav of navs) {
    const trigger = nav.querySelector<HTMLElement>(".framer-TYMUs");
    if (!trigger) continue;

    const closedNavVariant = variantClass(nav);
    const openNav = closedNavVariant
      ? NAV_OPEN_VARIANTS[closedNavVariant]
      : undefined;
    const closedNavName = nav.getAttribute("data-framer-name") ?? "";
    const closedTriggerVariant = variantClass(trigger);
    const closedTriggerName = trigger.getAttribute("data-framer-name") ?? "Closed";
    const icon = trigger.querySelector<HTMLElement>('[data-framer-name="Icon"]');
    const closedIconBg = icon?.style.backgroundImage ?? "";

    /**
     * The nav lives in its own `position: fixed` container. Lifting that
     * container above the panel keeps the logo and the X painted on top of the
     * full-screen ground and keeps the X clickable, which is what makes the
     * trigger a real close button.
     */
    const navLayer = ((): HTMLElement => {
      let el: HTMLElement | null = nav;
      while (el && el !== document.body) {
        const position = getComputedStyle(el).position;
        if (position === "fixed" || position === "sticky") return el;
        el = el.parentElement;
      }
      return nav;
    })();
    const navLayerZ = navLayer.style.zIndex;

    const panelId = nextId("nav-menu");
    let overlay: MenuOverlay | null = null;
    let open = false;
    let locked = false;
    let lifted = false;
    /** Bumped on every state change so a stale tween cannot land a stale state. */
    let generation = 0;
    let running: { stop: () => void }[] = [];
    /** 0 = clipped shut, 1 = fully wiped open. Survives interruption. */
    let wipe = 0;

    trigger.setAttribute("role", "button");
    trigger.setAttribute("aria-haspopup", "dialog");
    trigger.setAttribute("aria-expanded", "false");
    trigger.setAttribute("aria-controls", panelId);
    trigger.setAttribute("aria-label", "Open menu");
    // The export renders the hamburger as a plain div, so it is not reachable
    // by keyboard and cannot receive focus back when the panel closes.
    const hadTabIndex = trigger.hasAttribute("tabindex");
    if (!hadTabIndex) trigger.setAttribute("tabindex", "0");

    const focusables = (): HTMLElement[] => {
      const list: HTMLElement[] = [trigger];
      if (overlay) {
        list.push(
          ...Array.from(
            overlay.overlay.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR),
          ).filter(isFocusable),
        );
      }
      return list;
    };

    const stopAll = () => {
      for (const controls of running) {
        try {
          controls.stop();
        } catch {
          /* a stopped animation must not block the rest */
        }
      }
      running = [];
    };

    /** Runs only when the exit has played all the way through. */
    const finishClose = (token: number) => {
      if (token !== generation || open) return;
      overlay?.overlay.remove();
      overlay = null;
      if (locked) {
        locked = false;
        unlockBodyScroll();
      }
      if (lifted) {
        lifted = false;
        navLayer.style.zIndex = navLayerZ;
      }
    };

    const setOpen = (value: boolean) => {
      if (value === open) return;
      open = value;
      generation += 1;
      const token = generation;
      const reduce = prefersReducedMotion();

      // Both directions animate from wherever the panel currently is, so
      // tapping open/close/open mid-flight never snaps.
      stopAll();

      if (value) {
        const fresh = !overlay;
        if (!overlay) overlay = buildMenuOverlay(root, panelId);
        if (!overlay) {
          open = false;
          return;
        }
        const { overlay: panel, sheet, stagger } = overlay;

        if (fresh) {
          wipe = 0;
          paintWipe(panel, 0);
          for (const el of stagger) {
            el.style.opacity = String(MENU_ITEM_FROM_OPACITY);
            el.style.transform = `translateY(${MENU_ITEM_FROM_Y}px)`;
          }
          document.body.appendChild(panel);
          // Tapping the ground outside the link column is the backdrop tap;
          // tapping a link closes the menu behind the navigation.
          panel.addEventListener(
            "click",
            (event) => {
              const target = event.target as Element | null;
              if (target?.closest("a")) {
                setOpen(false);
                return;
              }
              if (!target || !sheet.contains(target)) setOpen(false);
            },
            { signal },
          );
        }

        panel.removeAttribute("aria-hidden");
        panel.style.pointerEvents = "";
        panel.style.setProperty(
          "--site-menu-top",
          `${Math.round(nav.getBoundingClientRect().height)}px`,
        );

        if (!locked) {
          locked = true;
          lockBodyScroll();
        }
        if (!lifted) {
          lifted = true;
          navLayer.style.zIndex = "2147483001";
        }

        if (openNav && closedNavVariant) {
          swapVariantClass(nav, closedNavVariant, openNav.cls);
          nav.setAttribute("data-framer-name", openNav.name);
        }
        swapVariantClass(trigger, closedTriggerVariant, HAMBURGER_OPEN_CLASS);
        trigger.setAttribute("data-framer-name", "Open State");
        if (icon) icon.style.backgroundImage = HAMBURGER_OPEN_ICON;
        trigger.setAttribute("aria-expanded", "true");
        trigger.setAttribute("aria-label", "Close menu");

        if (reduce) {
          wipe = 1;
          paintWipe(panel, 1);
          for (const el of stagger) {
            el.style.opacity = "1";
            el.style.transform = "none";
          }
        } else {
          running.push(
            animate(wipe, 1, {
              ...MENU_SPRING_IN,
              onUpdate: (v: number) => {
                wipe = v;
                paintWipe(panel, v);
              },
              onComplete: () => {
                wipe = 1;
                paintWipe(panel, 1);
              },
            }),
          );
          stagger.forEach((el, i) => {
            running.push(
              animate(
                el,
                { opacity: 1, y: 0 },
                {
                  ...MENU_SPRING_IN,
                  delay: MENU_CONTENT_DELAY + i * MENU_ITEM_STAGGER,
                },
              ),
            );
          });
        }

        focusables()[1]?.focus({ preventScroll: true });
      } else {
        const panel = overlay?.overlay;

        if (openNav && closedNavVariant) {
          swapVariantClass(nav, openNav.cls, closedNavVariant);
          nav.setAttribute("data-framer-name", closedNavName);
        }
        swapVariantClass(trigger, HAMBURGER_OPEN_CLASS, closedTriggerVariant);
        trigger.setAttribute("data-framer-name", closedTriggerName);
        if (icon) icon.style.backgroundImage = closedIconBg;
        trigger.setAttribute("aria-expanded", "false");
        trigger.setAttribute("aria-label", "Open menu");
        // Synchronously, while the exit is still playing: a keyboard user must
        // land back on the trigger the moment Escape is pressed.
        trigger.focus({ preventScroll: true });

        if (!panel || !overlay) {
          finishClose(token);
          return;
        }

        // Out of the a11y tree and inert for the whole of the exit, so the
        // menu can never be read or tapped while it is leaving.
        panel.setAttribute("aria-hidden", "true");
        panel.style.pointerEvents = "none";

        if (reduce) {
          finishClose(token);
          return;
        }

        for (const el of overlay.stagger) {
          running.push(animate(el, { opacity: 0 }, MENU_SPRING_OUT));
        }
        const wipeOut = animate(wipe, 0, {
          ...MENU_SPRING_OUT,
          onUpdate: (v: number) => {
            wipe = v;
            paintWipe(panel, v);
          },
        });
        running.push(wipeOut);
        wipeOut.then(() => finishClose(token));
      }
    };

    trigger.addEventListener(
      "click",
      (event) => {
        event.preventDefault();
        setOpen(!open);
      },
      { signal },
    );
    trigger.addEventListener(
      "keydown",
      (event) => {
        if (event.key === "Enter" || event.key === " " || event.key === "Spacebar") {
          event.preventDefault();
          setOpen(!open);
        }
      },
      { signal },
    );

    document.addEventListener(
      "keydown",
      (event) => {
        if (!open) return;
        if (event.key === "Escape") {
          event.preventDefault();
          setOpen(false);
          return;
        }
        if (event.key !== "Tab") return;
        const items = focusables();
        if (!items.length) return;
        const first = items[0];
        const last = items[items.length - 1];
        const active = document.activeElement as HTMLElement | null;
        if (event.shiftKey && (active === first || !items.includes(active as HTMLElement))) {
          event.preventDefault();
          last.focus();
        } else if (!event.shiftKey && active === last) {
          event.preventDefault();
          first.focus();
        }
      },
      { signal },
    );

    document.addEventListener(
      "pointerdown",
      (event) => {
        if (!open) return;
        const target = event.target as Node | null;
        if (trigger.contains(target) || overlay?.overlay.contains(target)) return;
        setOpen(false);
      },
      { signal },
    );

    // Browser chrome collapsing, an orientation change or a breakpoint switch
    // all move the nav's lower edge; the panel's top inset follows it.
    window.addEventListener(
      "resize",
      () => {
        if (!open || !overlay) return;
        overlay.overlay.style.setProperty(
          "--site-menu-top",
          `${Math.round(nav.getBoundingClientRect().height)}px`,
        );
      },
      { signal },
    );

    disposers.push(() => {
      // Teardown is immediate - an unmounting tree must not be left waiting on
      // an exit animation. `generation` invalidates any tween still in flight.
      generation += 1;
      open = false;
      stopAll();
      overlay?.overlay.remove();
      overlay = null;
      if (locked) {
        locked = false;
        unlockBodyScroll();
      }
      if (lifted) {
        lifted = false;
        navLayer.style.zIndex = navLayerZ;
      }
      if (openNav && closedNavVariant) {
        swapVariantClass(nav, openNav.cls, closedNavVariant);
        nav.setAttribute("data-framer-name", closedNavName);
      }
      swapVariantClass(trigger, HAMBURGER_OPEN_CLASS, closedTriggerVariant);
      trigger.setAttribute("data-framer-name", closedTriggerName);
      if (icon) icon.style.backgroundImage = closedIconBg;
      trigger.removeAttribute("role");
      trigger.removeAttribute("aria-haspopup");
      trigger.removeAttribute("aria-expanded");
      trigger.removeAttribute("aria-controls");
      trigger.removeAttribute("aria-label");
      if (!hadTabIndex) trigger.removeAttribute("tabindex");
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * Entry point                                                         *
 * ------------------------------------------------------------------ */

const bound = new WeakMap<HTMLElement, Disposer>();

export function initControls(root: HTMLElement): (() => void) | void {
  if (typeof window === "undefined") return undefined;

  // Idempotent: a second call tears the first one down before rebinding, so
  // handlers can never stack up (React StrictMode double-invokes effects).
  const previous = bound.get(root);
  if (previous) previous();

  const controller = new AbortController();
  const { signal } = controller;

  const disposers: Disposer[] = [
    initAccordions(root, signal),
    initSlideshows(root, signal),
    initCounters(root),
    initNavMenus(root, signal),
  ];

  const teardown = () => {
    if (bound.get(root) === teardown) bound.delete(root);
    controller.abort();
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* keep tearing the rest down */
      }
    }
  };

  bound.set(root, teardown);
  return teardown;
}
