"use client";

import { animate } from "motion/react";

/**
 * Restores the INTERACTIVE CONTROLS the Framer runtime used to drive.
 *
 * `page-full.tsx` is generated by scripts/opsra_extract.py and must never be
 * hand-edited, so everything here attaches by querying the export's own
 * markers (`data-framer-name`, aria-label, component structure).
 *
 * Every number below was measured against the original export running WITH
 * its Framer runtime (opsra/index.html) and cross-checked against the Framer
 * component modules in opsra/js/*.mjs. See the constants for the citations.
 */

/* ------------------------------------------------------------------ *
 * Measured transitions (from opsra/js/*.mjs + Playwright measurement) *
 * ------------------------------------------------------------------ */

/** Faq Item component variant transition: `{bounce:0,delay:0,duration:.4,type:'spring'}` */
const FAQ_SPRING = { type: "spring", duration: 0.4, bounce: 0 } as const;

/** Slideshow `transitionControl`: `{type:'spring',stiffness:200,damping:40}` */
const SLIDESHOW_SPRING = {
  type: "spring",
  stiffness: 200,
  damping: 40,
  mass: 1,
} as const;

/** Slideshow arrow `whileTap` transition: `{duration:.15}` */
const ARROW_TAP_SECONDS = 0.15;

/** Slideshow `intervalControl` — measured 3017ms between autoplay steps. */
const SLIDESHOW_INTERVAL_MS = 3000;

/**
 * Number Counter code component (plugin id 84d4c1) defaults, as used here:
 *   duration = 2  -> per-digit tween runs `duration * 0.8` = 1.6s
 *   ease     = "easeInOut"
 *   stagger  = digitIndex * 0.1s
 *   trigger  = useInView(ref, { amount: 0.5 }), fires once
 */
const COUNTER_DURATION_S = 2 * 0.8;
const COUNTER_STAGGER_S = 0.1;
const COUNTER_EASE = "easeInOut" as const;
const COUNTER_IN_VIEW_AMOUNT = 0.5;

/**
 * Stat counter targets.
 *
 * The digits are NOT in the export's DOM — the Framer code component receives
 * `targetNumber` as a prop, so the transcription only kept the rendered "0"s.
 * These are the values the original animates to, matched by card label
 * position (the port's labels are a 1:1 rewrite of the original's).
 *
 *   original "Faster workflow execution"  -> 3.2x   -> "More content shipped"
 *   original "Reduction in manual tasks"  ->  80%   -> "Less manual production"
 *   original "Smarter decision making"    -> 4.6x   -> "Faster brief to first cut"
 *   original "Increase in team output"    ->  65%   -> "Of spend under a hard cap"
 */
const COUNTER_TARGETS: Record<string, string> = {
  "More content shipped": "32",
  "Less manual production": "80",
  "Faster brief to first cut": "46",
  "Of spend under a hard cap": "65",
};
/** Positional fallback, in the same DOM order as the four stat cards. */
const COUNTER_TARGETS_BY_INDEX = ["32", "80", "46", "65"];

/**
 * FAQ answers for the five items the transcription could not carry over.
 *
 * In Framer the FAQ list is ONE component holding `answer1..answer6` as props;
 * only the open item's paragraph is ever in the DOM, so the static export kept
 * exactly one answer. These five are written from claims already made
 * elsewhere on this page (pricing bullets, feature copy, comparison cards).
 *
 * TODO(content): this copy belongs in scripts/opsra_content.py so the
 * extractor can emit it into page-full.tsx; it lives here only because that
 * file is generated and out of this module's scope.
 */
const FAQ_FALLBACK_ANSWERS: Record<string, string> = {
  "Is marketer.sh worth it for a solo operator?":
    "Yes. The $5 starter pack is enough to run a niche for a week and see the whole pipeline end to end, and credits never expire. There is no subscription and no card on file, so you only ever spend what you have already put in.",
  "How does marketer.sh keep costs predictable?":
    "Every job shows a cost estimate before it runs, and per-niche and global daily spend caps stop work before it goes past your budget. A full audit trail records every dollar and every asset, so nothing is spent without a line item behind it.",
  "Can marketer.sh publish to the channels we already use?":
    "Yes. Connect your channels once and marketer.sh publishes to every connected channel from a single brief, so one written brief becomes video, ads, and SEO articles that go out on the schedule you set.",
  "How quickly can we get the first video out?":
    "Most teams are running in minutes. Write one brief, approve the plan, and the agents handle ideation, production, and QA while you review, so the first cut lands far sooner than a manual production cycle.",
  "What makes marketer.sh different from other AI tools?":
    "Most tools stop at generation. marketer.sh runs the whole pipeline — ideation, production, QA, scheduling, and publishing — with human approval gates before anything publishes or spends, and a hard cap on every dollar.",
};

/* ------------------------------------------------------------------ *
 * Helpers                                                             *
 * ------------------------------------------------------------------ */

type Disposer = () => void;

const REDUCED_MOTION_QUERY = "(prefers-reduced-motion: reduce)";

function prefersReducedMotion(): boolean {
  return (
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia(REDUCED_MOTION_QUERY).matches
  );
}

let uid = 0;
function nextId(prefix: string): string {
  uid += 1;
  return `${prefix}-${uid}`;
}

function variantClass(el: Element): string | undefined {
  return Array.from(el.classList).find((c) => c.startsWith("framer-v-"));
}

function swapVariantClass(el: Element, from?: string, to?: string): void {
  if (from && from !== to) el.classList.remove(from);
  if (to) el.classList.add(to);
}

function isFocusable(el: Element): boolean {
  const node = el as HTMLElement;
  if (node.hasAttribute("disabled")) return false;
  if (node.getAttribute("aria-hidden") === "true") return false;
  if (node.tabIndex < 0) return false;
  const rect = node.getBoundingClientRect();
  return rect.width > 0 || rect.height > 0;
}

const FOCUSABLE_SELECTOR =
  'a[href], button, input, select, textarea, [tabindex]:not([tabindex="-1"])';

/* ------------------------------------------------------------------ *
 * 1. FAQ accordion                                                    *
 * ------------------------------------------------------------------ */

/**
 * The real collapsed state in the original is NOT `display:none` — the Framer
 * variant simply does not render the Paragraph node at all, and the item's
 * own `height:min-content` shrinks from 195px (open) to 88px (closed). The
 * open/closed variant classes also change padding (30px -> 24px 30px).
 *
 * Behaviour measured on the original:
 *   - exactly one item open at a time (radio-style)
 *   - clicking the OPEN item collapses it, so "all closed" is reachable
 *   - height animates with `{type:'spring',duration:.4,bounce:0}`, ~417ms
 *   - the paragraph never fades: opacity stays 1 throughout
 *   - the +/- icon swaps instantly (background-image swap, no tween)
 *   - Enter activates; Space does NOT in the original (we add it for a11y)
 */
function initAccordions(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  // An FAQ item is exactly "the element whose DIRECT child is a Faq Content
  // header row" — no hashed class names, no ancestor false positives.
  const allItems = Array.from(
    root.querySelectorAll<HTMLElement>(
      '[data-framer-name] > [data-framer-name="Faq Content"]',
    ),
  )
    .map((header) => header.parentElement)
    .filter((el): el is HTMLElement => el instanceof HTMLElement);

  // Group items by their shared list wrapper (desktop list vs mobile list).
  const groups = new Map<Element, HTMLElement[]>();
  for (const item of allItems) {
    const wrapper = item.parentElement?.parentElement;
    if (!wrapper) continue;
    const list = groups.get(wrapper);
    if (list) list.push(item);
    else groups.set(wrapper, [item]);
  }

  for (const [, items] of groups) {
    if (items.length < 2) continue;

    const openItem =
      items.find((i) => i.querySelector('[data-framer-name="Paragraph"]')) ??
      items[0];
    const closedItem = items.find((i) => i !== openItem);
    if (!closedItem) continue;

    const openName = openItem.getAttribute("data-framer-name") ?? "Open";
    const closedName = closedItem.getAttribute("data-framer-name") ?? "Close";
    const openVariant = variantClass(openItem);
    const closedVariant = variantClass(closedItem);

    const paragraphTemplate = openItem.querySelector<HTMLElement>(
      '[data-framer-name="Paragraph"]',
    );
    if (!paragraphTemplate) continue;

    // Icon variants: the open item shows "minus", the closed items "plus".
    const openIcon = openItem
      .querySelector('[data-framer-name="Icon Cover"]')
      ?.closest<HTMLElement>("[data-framer-name]:not([data-framer-name='Icon Cover'])");
    const closedIcon = closedItem
      .querySelector('[data-framer-name="Icon Cover"]')
      ?.closest<HTMLElement>("[data-framer-name]:not([data-framer-name='Icon Cover'])");
    const minus = openIcon
      ? {
          name: openIcon.getAttribute("data-framer-name") ?? "",
          variant: variantClass(openIcon),
          bg:
            openIcon.querySelector<HTMLElement>(
              '[data-framer-name="Icon Cover"]',
            )?.style.backgroundImage ?? "",
        }
      : null;
    const plus = closedIcon
      ? {
          name: closedIcon.getAttribute("data-framer-name") ?? "",
          variant: variantClass(closedIcon),
          bg:
            closedIcon.querySelector<HTMLElement>(
              '[data-framer-name="Icon Cover"]',
            )?.style.backgroundImage ?? "",
        }
      : null;

    type Entry = {
      item: HTMLElement;
      header: HTMLElement;
      panel: HTMLElement;
      heading: HTMLElement | null;
      createdPanel: boolean;
      originalTabIndex: string | null;
      initialName: string;
      initialVariant: string | undefined;
      open: boolean;
      /** Bumped on every toggle so a stale tween cannot land a stale state. */
      generation: number;
    };

    const entries: Entry[] = [];

    items.forEach((item) => {
      const header = item.querySelector<HTMLElement>(
        '[data-framer-name="Faq Content"]',
      );
      if (!header) return;
      const heading = item.querySelector<HTMLElement>(
        '[data-framer-name="Heading"]',
      );
      const question = heading?.textContent?.trim() ?? "";

      let panel = item.querySelector<HTMLElement>(
        '[data-framer-name="Paragraph"]',
      );
      let createdPanel = false;

      if (!panel) {
        // The original mounts this node only in the open variant. Recreate it
        // from the open item's own markup so the styling stays identical.
        const clone = paragraphTemplate.cloneNode(true) as HTMLElement;
        const p = clone.querySelector("p");
        const answer = FAQ_FALLBACK_ANSWERS[question];
        if (p && answer) p.textContent = answer;
        else if (p && !answer) p.textContent = "";
        item.appendChild(clone);
        panel = clone;
        createdPanel = true;
      }

      const panelId = nextId("faq-panel");
      panel.id = panelId;
      panel.setAttribute("role", "region");
      if (heading) {
        if (!heading.id) heading.id = nextId("faq-heading");
        panel.setAttribute("aria-labelledby", heading.id);
      }

      const originalTabIndex = item.getAttribute("tabindex");
      // Move the tab stop onto the header so the panel is not nested inside
      // the button, which is what a disclosure pattern requires.
      item.setAttribute("tabindex", "-1");
      header.setAttribute("role", "button");
      header.setAttribute("tabindex", "0");
      header.setAttribute("aria-controls", panelId);

      const open = item === openItem;
      entries.push({
        item,
        header,
        panel,
        heading,
        createdPanel,
        originalTabIndex,
        initialName: item.getAttribute("data-framer-name") ?? "",
        initialVariant: variantClass(item),
        open,
        generation: 0,
      });

      // Items whose answer we could not recover stay inert rather than
      // opening onto an empty panel.
      const hasAnswer = (panel.textContent ?? "").trim().length > 0;
      if (!hasAnswer) {
        header.setAttribute("aria-disabled", "true");
      }

      applyState(entries[entries.length - 1], open, /* animateIt */ false);
    });

    function applyState(entry: Entry, open: boolean, animateIt: boolean): void {
      const { item, header, panel } = entry;
      const reduce = prefersReducedMotion();

      item.setAttribute("data-framer-name", open ? openName : closedName);
      swapVariantClass(
        item,
        open ? closedVariant : openVariant,
        open ? openVariant : closedVariant,
      );
      header.setAttribute("aria-expanded", open ? "true" : "false");

      const icon = open ? minus : plus;
      const iconHost = item
        .querySelector('[data-framer-name="Icon Cover"]')
        ?.closest<HTMLElement>(
          "[data-framer-name]:not([data-framer-name='Icon Cover'])",
        );
      if (icon && iconHost) {
        const cover = iconHost.querySelector<HTMLElement>(
          '[data-framer-name="Icon Cover"]',
        );
        iconHost.setAttribute("data-framer-name", icon.name);
        swapVariantClass(
          iconHost,
          variantClass(iconHost),
          icon.variant,
        );
        if (cover && icon.bg) cover.style.backgroundImage = icon.bg;
      }

      if (!animateIt || reduce) {
        panel.hidden = !open;
        item.style.height = "";
        item.style.overflow = "";
        entry.open = open;
        return;
      }

      const from = item.offsetHeight;
      panel.hidden = !open;
      item.style.height = "auto";
      const to = item.offsetHeight;
      item.style.height = `${from}px`;
      item.style.overflow = "hidden";
      // Keep the collapsing panel visible (and out of the a11y tree) while
      // the height animates, then unmount it from the a11y tree for good.
      if (!open) {
        panel.hidden = false;
        panel.setAttribute("aria-hidden", "true");
      } else {
        panel.removeAttribute("aria-hidden");
      }

      entry.generation += 1;
      const generation = entry.generation;
      const controls = animate(
        item,
        { height: [`${from}px`, `${to}px`] },
        FAQ_SPRING,
      );
      controls.then(() => {
        if (entry.generation !== generation) return;
        item.style.height = "";
        item.style.overflow = "";
        panel.hidden = !open;
        panel.removeAttribute("aria-hidden");
      });
      disposers.push(() => controls.stop());
      entry.open = open;
    }

    const toggle = (entry: Entry) => {
      if (entry.header.getAttribute("aria-disabled") === "true") return;
      const willOpen = !entry.open;
      for (const other of entries) {
        if (other === entry) continue;
        if (other.open) applyState(other, false, true);
      }
      applyState(entry, willOpen, true);
    };

    for (const entry of entries) {
      entry.item.addEventListener(
        "click",
        (event) => {
          // Never swallow a real link inside the card.
          if ((event.target as Element | null)?.closest("a")) return;
          toggle(entry);
        },
        { signal },
      );
      entry.header.addEventListener(
        "keydown",
        (event) => {
          if (event.key === "Enter" || event.key === " " || event.key === "Spacebar") {
            event.preventDefault();
            toggle(entry);
          }
        },
        { signal },
      );
    }

    disposers.push(() => {
      for (const entry of entries) {
        const { item, header, panel, originalTabIndex, createdPanel } = entry;
        item.style.height = "";
        item.style.overflow = "";
        item.setAttribute("data-framer-name", entry.initialName);
        swapVariantClass(item, variantClass(item), entry.initialVariant);
        if (originalTabIndex === null) item.removeAttribute("tabindex");
        else item.setAttribute("tabindex", originalTabIndex);
        header.removeAttribute("role");
        header.removeAttribute("tabindex");
        header.removeAttribute("aria-controls");
        header.removeAttribute("aria-expanded");
        header.removeAttribute("aria-disabled");
        if (createdPanel) panel.remove();
        else {
          panel.hidden = false;
          panel.removeAttribute("role");
          panel.removeAttribute("aria-labelledby");
          panel.removeAttribute("aria-hidden");
        }
      }
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 2. Slideshow / carousel                                             *
 * ------------------------------------------------------------------ */

/**
 * `section.framer-slideshow` is Framer's Slideshow code component. It sits in
 * the Comparison section (two instances) — the brief called it the social
 * proof carousel, but the social proof block has no slideshow.
 *
 * The arrows ship `disabled`, `pointer-events:none` and `opacity:0` because
 * that is the component's PRE-MEASUREMENT state
 * (`disabled: !(isCanvas || isInitialized)`); the live runtime flips all of it
 * on as soon as it has measured the items. It also clones the six slots to
 * four copies (`nt = et * 4`) so the loop never runs dry — the static export
 * only kept one copy, so we rebuild the other three.
 *
 * Position is composed from two independent offsets so this module can run
 * alongside `ticker.tsx`, which owns the slideshow's 3s autoplay and writes
 * `transform` on the same `<ul>` every frame:
 *
 *   final position = translateX(autoplay, ticker.tsx) + marginLeft(arrows, here)
 *
 * If no external driver is detected we take the autoplay on ourselves too, so
 * this file is still self-sufficient.
 *
 * Two deliberate deviations from the original, both flagged in the report:
 *   - this instance sets `showMouseControls:false`, so the original leaves the
 *     arrows at `display:none` — invisible AND unreachable. We lay them out at
 *     `opacity:0` and fade them in on hover/focus, so the at-rest pixels are
 *     unchanged while the control is genuinely operable and focusable.
 *   - the original never disables the arrows at the ends, because the track is
 *     infinite. Neither do we.
 */
function initSlideshows(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  const slideshows = Array.from(
    root.querySelectorAll<HTMLElement>("section.framer-slideshow"),
  );

  for (const section of slideshows) {
    if (section.dataset.controlsSlideshow) continue;
    const track = section.querySelector<HTMLElement>("ul");
    const prev = section.querySelector<HTMLButtonElement>(
      'button[aria-label="Previous"]',
    );
    const next = section.querySelector<HTMLButtonElement>(
      'button[aria-label="Next"]',
    );
    if (!track) continue;

    const originals = Array.from(track.children) as HTMLElement[];
    const count = originals.length;
    if (count < 2) continue;

    // ticker.tsx stamps `will-change: transform` on the list it is driving.
    const externalAutoplay = track.style.willChange === "transform";
    section.dataset.controlsSlideshow = externalAutoplay ? "arrows" : "full";

    const trackId = nextId("slideshow-track");
    track.id = trackId;

    // --- rebuild the 4x looping track (matches `nt = et * 4` in the runtime)
    const COPIES = 4;
    const clones: HTMLElement[] = [];
    for (let copy = 1; copy < COPIES; copy += 1) {
      for (const li of originals) {
        const clone = li.cloneNode(true) as HTMLElement;
        clone.setAttribute("aria-hidden", "true");
        clone
          .querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)
          .forEach((el) => el.setAttribute("tabindex", "-1"));
        clones.push(clone);
        track.appendChild(clone);
      }
    }

    const gap = Number.parseFloat(getComputedStyle(track).gap || "0") || 0;
    const measure = () => {
      const first = originals[0]?.firstElementChild as HTMLElement | null;
      return (first?.getBoundingClientRect().width ?? 0) + gap;
    };

    let step = measure();
    let total = step * count;
    // The page module passes `startFrom: 1`, and the export's SSR transform
    // (`translateX(calc(-1 * (100% + 11px)))`) already parks the track one
    // slot in, so our own offset starts at 0 on slide index 1.
    const START_INDEX = 1;
    let index = START_INDEX;

    /** Our own offset only ever spans one loop length: (-total, 0]. */
    const wrap = (value: number) => {
      if (total <= 0) return 0;
      return -((((-value % total) + total) % total));
    };

    const previousMargin = track.style.marginLeft;
    let offset = 0;
    const paint = (value: number) => {
      offset = value;
      track.style.marginLeft = `${value.toFixed(2)}px`;
    };
    paint(0);

    // Static, accurate button names; a polite live region carries the position
    // so a focused button's accessible name never changes under the user.
    section.setAttribute("aria-roledescription", "carousel");
    const status = document.createElement("span");
    status.setAttribute("aria-live", "polite");
    status.style.cssText =
      "position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0";
    section.appendChild(status);
    disposers.push(() => status.remove());

    const announce = () => {
      const position = ((index % count) + count) % count;
      const label = originals[position]?.textContent?.trim() ?? "";
      status.textContent = `Slide ${position + 1} of ${count}${label ? `: ${label}` : ""}`;
    };

    let current: ReturnType<typeof animate> | null = null;

    const goTo = (delta: number) => {
      index += delta;
      const settled = wrap(-(index - START_INDEX) * step);
      const from = offset;
      // Unwrap the target so the tween always travels the asked direction.
      let to = settled;
      if (delta > 0) while (to >= from) to -= total;
      else while (to <= from) to += total;

      current?.stop();
      current = null;

      if (prefersReducedMotion()) {
        paint(settled);
        announce();
        return;
      }

      current = animate(from, to, {
        ...SLIDESHOW_SPRING,
        onUpdate: (v: number) => {
          offset = v;
          track.style.marginLeft = `${v.toFixed(2)}px`;
        },
        onComplete: () => paint(settled),
      });
      announce();
    };

    // --- enable the arrows: exactly what the runtime does once measured
    const arrowWrapper = prev?.parentElement as HTMLElement | null;
    const restoreArrow: Disposer[] = [];
    for (const button of [prev, next]) {
      if (!button) continue;
      const before = {
        disabled: button.disabled,
        pointerEvents: button.style.pointerEvents,
        cursor: button.style.cursor,
        display: button.style.display,
        opacity: button.style.opacity,
        transition: button.style.transition,
      };
      button.disabled = false;
      button.removeAttribute("disabled");
      button.style.pointerEvents = "auto";
      button.style.cursor = "pointer";
      button.style.display = "block";
      button.style.opacity = "0";
      button.style.transition = `opacity ${ARROW_TAP_SECONDS}s ease-out, transform ${ARROW_TAP_SECONDS}s ease-out`;
      button.setAttribute("aria-controls", trackId);
      restoreArrow.push(() => {
        button.disabled = before.disabled;
        if (before.disabled) button.setAttribute("disabled", "");
        button.style.pointerEvents = before.pointerEvents;
        button.style.cursor = before.cursor;
        button.style.display = before.display;
        button.style.opacity = before.opacity;
        button.style.transition = before.transition;
        button.removeAttribute("aria-controls");
      });
    }
    if (arrowWrapper) {
      const beforeOpacity = arrowWrapper.style.opacity;
      arrowWrapper.style.opacity = "1";
      restoreArrow.push(() => {
        arrowWrapper.style.opacity = beforeOpacity;
      });
    }
    disposers.push(() => {
      for (const restore of restoreArrow) {
        try {
          restore();
        } catch {
          /* keep restoring the rest */
        }
      }
    });
    announce();

    const setArrowsVisible = (visible: boolean) => {
      for (const button of [prev, next]) {
        if (button) button.style.opacity = visible ? "1" : "0";
      }
    };
    section.addEventListener("pointerenter", () => setArrowsVisible(true), {
      signal,
    });
    section.addEventListener("pointerleave", () => setArrowsVisible(false), {
      signal,
    });
    section.addEventListener("focusin", () => setArrowsVisible(true), {
      signal,
    });
    section.addEventListener(
      "focusout",
      (event) => {
        if (!section.contains(event.relatedTarget as Node | null)) {
          setArrowsVisible(false);
        }
      },
      { signal },
    );

    /** The component's own arrow feedback: `whileTap {scale:.9}`, 0.15s. */
    const tapFeedback = (button: HTMLButtonElement) => {
      if (prefersReducedMotion()) return;
      button.style.transform = "scale(0.9)";
      window.setTimeout(() => {
        button.style.transform = "none";
      }, ARROW_TAP_SECONDS * 1000);
    };

    // --- autoplay: 3s per step while in view (`playOffscreen: false`).
    // Skipped when ticker.tsx is already running it on this element.
    let timer: number | undefined;
    let inView = false;

    const stopAutoplay = () => {
      if (timer !== undefined) window.clearTimeout(timer);
      timer = undefined;
    };
    const tick = () => {
      timer = window.setTimeout(() => {
        goTo(1);
        tick();
      }, SLIDESHOW_INTERVAL_MS);
    };
    const restartAutoplay = () => {
      stopAutoplay();
      if (externalAutoplay) return;
      if (inView && !prefersReducedMotion()) tick();
    };

    prev?.addEventListener(
      "click",
      () => {
        tapFeedback(prev);
        goTo(-1);
        restartAutoplay();
      },
      { signal },
    );
    next?.addEventListener(
      "click",
      () => {
        tapFeedback(next);
        goTo(1);
        restartAutoplay();
      },
      { signal },
    );

    const io = new IntersectionObserver(
      (entries) => {
        inView = entries.some((e) => e.isIntersecting);
        restartAutoplay();
      },
      { threshold: 0 },
    );
    io.observe(section);

    const onResize = () => {
      const resized = measure();
      if (!resized || Math.abs(resized - step) < 0.5) return;
      step = resized;
      total = step * count;
      paint(wrap(-(index - START_INDEX) * step));
    };
    window.addEventListener("resize", onResize, { signal });

    const mq = window.matchMedia(REDUCED_MOTION_QUERY);
    const onMq = () => restartAutoplay();
    mq.addEventListener("change", onMq);

    disposers.push(() => {
      // Cleared first: a stranded guard flag would make the next mount skip
      // rebuilding the 4x track (React StrictMode remounts this effect).
      delete section.dataset.controlsSlideshow;
      stopAutoplay();
      current?.stop();
      io.disconnect();
      mq.removeEventListener("change", onMq);
      clones.forEach((c) => c.remove());
      track.style.marginLeft = previousMargin;
      track.removeAttribute("id");
      section.removeAttribute("aria-roledescription");
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 3. Stat counters                                                    *
 * ------------------------------------------------------------------ */

/**
 * The Number Counter code component renders one "digit slot" per digit
 * (`min-width:0.6em`, `overflow:hidden`) holding an absolutely positioned
 * digit at `translateY(0%)`. It animates a float per slot and paints
 * `floor(v)` plus the next digit offset by the fraction, i.e. an odometer.
 */
function initCounters(root: HTMLElement): Disposer {
  const disposers: Disposer[] = [];

  const containers = Array.from(
    root.querySelectorAll<HTMLElement>('[data-code-component-plugin-id="84d4c1"]'),
  );
  if (!containers.length) return () => {};

  // Label -> target, with a positional fallback keyed on visual order.
  const labelFor = (container: HTMLElement): string => {
    const card = container.closest<HTMLElement>('[data-framer-name="Numbers and Icon"]')
      ?.parentElement;
    if (!card) return "";
    const clone = card.cloneNode(true) as HTMLElement;
    clone
      .querySelectorAll('[data-code-component-plugin-id="84d4c1"]')
      .forEach((n) => n.remove());
    return (clone.textContent ?? "").trim();
  };

  let ordinal = 0;
  const seenLabels = new Map<string, number>();

  for (const container of containers) {
    const slots = Array.from(
      container.querySelectorAll<HTMLElement>('div[style*="0.6em"]'),
    ).filter((el) => el.firstElementChild);
    if (!slots.length) continue;

    const label = labelFor(container);
    let target = COUNTER_TARGETS[label];
    if (!target) {
      // Fall back to position: containers repeat once per breakpoint variant.
      let bucket = seenLabels.get(label);
      if (bucket === undefined) {
        bucket = ordinal % COUNTER_TARGETS_BY_INDEX.length;
        seenLabels.set(label, bucket);
        ordinal += 1;
      }
      target = COUNTER_TARGETS_BY_INDEX[bucket];
    }

    const digits = target
      .split("")
      .filter((c) => c >= "0" && c <= "9")
      .map((c) => Number.parseInt(c, 10));
    if (!digits.length) continue;

    const paint = (slotIndex: number, value: number) => {
      const slot = slots[slotIndex];
      if (!slot) return;
      const base = slot.firstElementChild as HTMLElement | null;
      if (!base) return;
      const whole = Math.floor(value);
      const frac = value - whole;
      base.textContent = String(Math.max(0, Math.min(9, whole)));
      base.style.transform = `translateY(${(frac * -100).toFixed(3)}%)`;

      const upcoming = whole + 1;
      let follower = slot.children[1] as HTMLElement | undefined;
      if (frac > 0 && upcoming <= 9) {
        if (!follower) {
          follower = base.cloneNode(false) as HTMLElement;
          follower.setAttribute("aria-hidden", "true");
          slot.appendChild(follower);
        }
        follower.textContent = String(upcoming);
        follower.style.transform = `translateY(${((1 - frac) * 100).toFixed(3)}%)`;
      } else if (follower) {
        follower.remove();
      }
    };

    const settle = () => {
      digits.forEach((d, i) => {
        const slot = slots[i];
        if (!slot) return;
        const extra = slot.children[1];
        if (extra) extra.remove();
        const base = slot.firstElementChild as HTMLElement | null;
        if (!base) return;
        base.textContent = String(d);
        base.style.transform = "translateY(0%)";
      });
    };

    let started = false;
    const run = () => {
      if (started) return;
      started = true;

      if (prefersReducedMotion()) {
        settle();
        return;
      }

      digits.forEach((to, i) => {
        const controls = animate(0, to, {
          duration: COUNTER_DURATION_S,
          ease: COUNTER_EASE,
          delay: i * COUNTER_STAGGER_S,
          onUpdate: (v: number) => paint(i, v),
          onComplete: () => paint(i, to),
        });
        disposers.push(() => controls.stop());
      });
    };

    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          run();
          io.disconnect();
        }
      },
      { threshold: COUNTER_IN_VIEW_AMOUNT },
    );
    io.observe(container);
    disposers.push(() => io.disconnect());
    disposers.push(() => {
      slots.forEach((slot) => {
        const extra = slot.children[1];
        if (extra) extra.remove();
        const base = slot.firstElementChild as HTMLElement | null;
        if (base) {
          base.textContent = "0";
          base.style.transform = "translateY(0%)";
        }
      });
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * 4. Mobile / tablet nav menu                                         *
 * ------------------------------------------------------------------ */

/**
 * The Nav component has five variants; the hamburger ("Menu Icon", variants
 * Closed / Open State) flips the nav from Phone -> Phone Open or
 * Tablet -> Tab Open, which is the only condition under which the
 * `.framer-bwjtjp` Menu panel is rendered at all. The panel appears instantly
 * (Framer's variant root is `initial:false`, so there is no enter animation)
 * and clicking any menu link closes it again.
 *
 * The transcription only kept the closed variants, so the panel is rebuilt
 * here from the export's own classes (all present in site.css) with the link
 * labels/hrefs and CTA cloned out of the Desktop nav so nothing is invented.
 */
const NAV_OPEN_VARIANTS: Record<string, { cls: string; name: string }> = {
  // Phone -> Phone Open
  "framer-v-1bdgyp0": { cls: "framer-v-1neiqul", name: "Phone Open" },
  // Tablet -> Tab Open
  "framer-v-l1gk15": { cls: "framer-v-1t1qv3v", name: "Tab Open" },
};

const HAMBURGER_OPEN_CLASS = "framer-v-jcqq8b";

/** The "Open State" X glyph, lifted verbatim from the running original. */
const HAMBURGER_OPEN_ICON =
  'url("data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 xmlns:xlink=%22http://www.w3.org/1999/xlink%22 viewBox=%220 0 22 22%22><path d=%22M 5.123 5.35 C 5.389 5.083 5.821 5.083 6.087 5.35 L 10.795 10.057 L 9.831 11.021 L 5.123 6.314 C 4.857 6.047 4.857 5.616 5.123 5.35 Z M 16.694 15.956 C 16.96 16.222 16.96 16.654 16.694 16.92 C 16.428 17.187 15.996 17.187 15.73 16.92 L 10.795 11.986 L 11.759 11.021 Z M 6.087 16.693 L 10.795 11.986 L 9.831 11.021 L 5.123 15.729 C 4.857 15.995 4.857 16.427 5.123 16.693 C 5.389 16.959 5.821 16.959 6.087 16.693 Z M 16.694 6.086 C 16.96 5.82 16.96 5.389 16.694 5.122 C 16.428 4.856 15.996 4.856 15.73 5.122 L 10.795 10.057 L 11.759 11.021 Z%22 fill=%22rgb(255,255,255)%22></path></svg>")';

/** Menu link wrapper classes, in the order the original renders them. */
const MENU_LINK_CLASSES = [
  "framer-1ff9kds",
  "framer-19wp6jq",
  "framer-1jrfh26",
  "framer-e4qt6s",
  "framer-iiama6",
  "framer-xs02o7",
];

function buildMenuPanel(root: HTMLElement, panelId: string): HTMLElement | null {
  const source = Array.from(root.querySelectorAll<HTMLElement>("nav")).find(
    (n) => n.querySelector('[data-framer-name="Nav Links Wrap"]'),
  );
  if (!source) return null;

  const links = Array.from(
    source.querySelectorAll<HTMLElement>(
      '[data-framer-name="Nav Links Wrap"] [data-framer-name="Text Button"]',
    ),
  );
  const cta = source.querySelector<HTMLElement>(
    '[data-framer-name="Primary Button"]',
  );

  const panel = document.createElement("div");
  panel.className = "framer-bwjtjp";
  panel.setAttribute("data-border", "true");
  panel.setAttribute("data-framer-name", "Menu");
  panel.id = panelId;
  panel.setAttribute("role", "dialog");
  panel.setAttribute("aria-modal", "false");
  panel.setAttribute("aria-label", "Site menu");
  panel.style.cssText = [
    "--border-bottom-width: 1px",
    "--border-color: var(--token-6f736482-00f8-4928-8b5f-342942aa76e8, rgb(42, 60, 58))",
    "--border-left-width: 1px",
    "--border-right-width: 1px",
    "--border-style: solid",
    "--border-top-width: 1px",
    "background-color: var(--token-5ba75b1b-325e-49a3-a831-486521e69d36, rgb(32, 45, 44))",
    "border-radius: 2px",
    "opacity: 1",
  ].join("; ");

  const wrap = document.createElement("div");
  wrap.className = "framer-13vrg8f";
  wrap.setAttribute("data-framer-name", "Nav Links Wrap");
  wrap.style.borderRadius = "8px";

  links.forEach((link, i) => {
    const anchor = link.querySelector("a");
    const item = document.createElement("div");
    item.className = MENU_LINK_CLASSES[i] ?? MENU_LINK_CLASSES[MENU_LINK_CLASSES.length - 1];
    item.setAttribute("data-framer-name", "Text Button");
    item.setAttribute("data-highlight", "true");
    item.setAttribute("data-framer-component-type", "RichTextContainer");
    item.style.cssText = [
      "--extracted-r6o4lv: var(--token-8d29ccb4-0aa8-491a-8788-1d8fc78460b8, rgb(129, 152, 149))",
      "--framer-paragraph-spacing: 0px",
      "transform: none",
      "opacity: 1",
    ].join("; ");

    const p = document.createElement("p");
    p.className = "framer-text framer-styles-preset-x1k7r";
    p.setAttribute("data-styles-preset", "MuF1m_OLL");
    p.setAttribute("dir", "auto");
    p.style.setProperty(
      "--framer-text-color",
      "var(--extracted-r6o4lv, var(--token-8d29ccb4-0aa8-491a-8788-1d8fc78460b8, rgb(129, 152, 149)))",
    );

    const a = document.createElement("a");
    a.className = "framer-text framer-styles-preset-de286j";
    a.setAttribute("data-styles-preset", "e_3Rjy2bC");
    a.setAttribute("href", anchor?.getAttribute("href") ?? "#");
    a.textContent = anchor?.textContent ?? link.textContent ?? "";

    p.appendChild(a);
    item.appendChild(p);
    wrap.appendChild(item);
  });

  panel.appendChild(wrap);

  if (cta) {
    const ctaWrap = document.createElement("div");
    ctaWrap.className = "framer-1szd0kb-container";
    ctaWrap.style.opacity = "1";
    const clone = cta.cloneNode(true) as HTMLElement;
    clone.removeAttribute("id");
    ctaWrap.appendChild(clone);
    panel.appendChild(ctaWrap);
  }

  return panel;
}

function initNavMenus(root: HTMLElement, signal: AbortSignal): Disposer {
  const disposers: Disposer[] = [];

  const navs = Array.from(root.querySelectorAll<HTMLElement>("nav")).filter(
    (nav) => nav.querySelector(".framer-TYMUs"),
  );

  for (const nav of navs) {
    const trigger = nav.querySelector<HTMLElement>(".framer-TYMUs");
    const host = nav.querySelector<HTMLElement>('[data-framer-name="Sub Container"]');
    if (!trigger || !host) continue;

    const closedNavVariant = variantClass(nav);
    const openNav = closedNavVariant
      ? NAV_OPEN_VARIANTS[closedNavVariant]
      : undefined;
    const closedNavName = nav.getAttribute("data-framer-name") ?? "";
    const closedTriggerVariant = variantClass(trigger);
    const closedTriggerName = trigger.getAttribute("data-framer-name") ?? "Closed";
    const icon = trigger.querySelector<HTMLElement>('[data-framer-name="Icon"]');
    const closedIconBg = icon?.style.backgroundImage ?? "";

    const panelId = nextId("nav-menu");
    let panel: HTMLElement | null = null;
    let open = false;
    let lastFocus: HTMLElement | null = null;

    trigger.setAttribute("role", "button");
    trigger.setAttribute("aria-haspopup", "menu");
    trigger.setAttribute("aria-expanded", "false");
    trigger.setAttribute("aria-controls", panelId);
    trigger.setAttribute("aria-label", "Open menu");

    const focusables = (): HTMLElement[] => {
      const list: HTMLElement[] = [trigger];
      if (panel) {
        list.push(
          ...Array.from(
            panel.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR),
          ).filter(isFocusable),
        );
      }
      return list;
    };

    const setOpen = (value: boolean) => {
      if (value === open) return;
      open = value;

      if (value) {
        lastFocus = (document.activeElement as HTMLElement | null) ?? trigger;
        panel = buildMenuPanel(root, panelId);
        if (panel) {
          host.appendChild(panel);
          panel.addEventListener(
            "click",
            (event) => {
              if ((event.target as Element | null)?.closest("a")) setOpen(false);
            },
            { signal },
          );
        }
        if (openNav && closedNavVariant) {
          swapVariantClass(nav, closedNavVariant, openNav.cls);
          nav.setAttribute("data-framer-name", openNav.name);
        }
        swapVariantClass(trigger, closedTriggerVariant, HAMBURGER_OPEN_CLASS);
        trigger.setAttribute("data-framer-name", "Open State");
        if (icon) icon.style.backgroundImage = HAMBURGER_OPEN_ICON;
        trigger.setAttribute("aria-expanded", "true");
        trigger.setAttribute("aria-label", "Close menu");
        const first = focusables()[1];
        first?.focus();
      } else {
        panel?.remove();
        panel = null;
        if (openNav && closedNavVariant) {
          swapVariantClass(nav, openNav.cls, closedNavVariant);
          nav.setAttribute("data-framer-name", closedNavName);
        }
        swapVariantClass(trigger, HAMBURGER_OPEN_CLASS, closedTriggerVariant);
        trigger.setAttribute("data-framer-name", closedTriggerName);
        if (icon) icon.style.backgroundImage = closedIconBg;
        trigger.setAttribute("aria-expanded", "false");
        trigger.setAttribute("aria-label", "Open menu");
        (lastFocus ?? trigger).focus();
        lastFocus = null;
      }
    };

    trigger.addEventListener(
      "click",
      (event) => {
        event.preventDefault();
        setOpen(!open);
      },
      { signal },
    );
    trigger.addEventListener(
      "keydown",
      (event) => {
        if (event.key === "Enter" || event.key === " " || event.key === "Spacebar") {
          event.preventDefault();
          setOpen(!open);
        }
      },
      { signal },
    );

    document.addEventListener(
      "keydown",
      (event) => {
        if (!open) return;
        if (event.key === "Escape") {
          event.preventDefault();
          setOpen(false);
          return;
        }
        if (event.key !== "Tab") return;
        const items = focusables();
        if (!items.length) return;
        const first = items[0];
        const last = items[items.length - 1];
        const active = document.activeElement as HTMLElement | null;
        if (event.shiftKey && (active === first || !items.includes(active as HTMLElement))) {
          event.preventDefault();
          last.focus();
        } else if (!event.shiftKey && active === last) {
          event.preventDefault();
          first.focus();
        }
      },
      { signal },
    );

    document.addEventListener(
      "pointerdown",
      (event) => {
        if (!open) return;
        const target = event.target as Node | null;
        if (trigger.contains(target) || panel?.contains(target)) return;
        setOpen(false);
      },
      { signal },
    );

    disposers.push(() => {
      if (open) setOpen(false);
      trigger.removeAttribute("role");
      trigger.removeAttribute("aria-haspopup");
      trigger.removeAttribute("aria-expanded");
      trigger.removeAttribute("aria-controls");
      trigger.removeAttribute("aria-label");
    });
  }

  return () => {
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* one failure must not strand the remaining restores */
      }
    }
  };
}

/* ------------------------------------------------------------------ *
 * Entry point                                                         *
 * ------------------------------------------------------------------ */

const bound = new WeakMap<HTMLElement, Disposer>();

export function initControls(root: HTMLElement): (() => void) | void {
  if (typeof window === "undefined") return undefined;

  // Idempotent: a second call tears the first one down before rebinding, so
  // handlers can never stack up (React StrictMode double-invokes effects).
  const previous = bound.get(root);
  if (previous) previous();

  const controller = new AbortController();
  const { signal } = controller;

  const disposers: Disposer[] = [
    initAccordions(root, signal),
    initSlideshows(root, signal),
    initCounters(root),
    initNavMenus(root, signal),
  ];

  const teardown = () => {
    if (bound.get(root) === teardown) bound.delete(root);
    controller.abort();
    for (const dispose of disposers) {
      try {
        dispose();
      } catch {
        /* keep tearing the rest down */
      }
    }
  };

  bound.set(root, teardown);
  return teardown;
}
