"use client";

import { useEffect } from "react";

import { initControls } from "./controls";
import { initProductMenu } from "./product-menu";
import { initReveal } from "./reveal";
import { initTicker } from "./ticker";

/**
 * Restores the motion the Framer runtime used to drive.
 *
 * The export's 306KB stylesheet contains ZERO @keyframes and ZERO
 * `animation:` declarations — every animation on that site was JavaScript.
 * Stripping the runtime therefore removed all of it, leaving only the 50
 * CSS `:hover` rules.
 *
 * `page-full.tsx` is generated by scripts/opsra_extract.py and must not be
 * hand-edited, so each system attaches by querying the DOM for the
 * export's own markers rather than by wrapping elements in components.
 * Each init owns one file and returns its own cleanup.
 */
export function SiteMotion() {
  useEffect(() => {
    const root = document.getElementById("main");
    if (!root) return;
    const teardown = [
      initReveal(root),
      initTicker(root),
      initControls(root),
      initProductMenu(root),
    ];
    return () => teardown.forEach((fn) => fn?.());
  }, []);

  return null;
}
