"use client";

import { animate } from "motion";
import type { AnimationOptions } from "motion";

/**
 * The desktop "Product" dropdown.
 *
 * The nav lives in `components/site/shell.tsx`, which is generated by
 * scripts/opsra_extract.py from the Framer export and must never be
 * hand-edited — so, exactly like `reveal.tsx` / `ticker.tsx` / `controls.tsx`,
 * this attaches by querying the export's own markers:
 *
 *   nav[data-framer-name="Desktop"]
 *     └ [data-framer-name="Nav Links Wrap"]        (.framer-vtc2dc)
 *         └ [data-framer-name="Text Button"] > p > a   ← one per nav link
 *
 * The anchor whose text is "Features" is relabelled "Product" and becomes the
 * disclosure trigger; the panel is inserted as the trigger wrapper's next
 * sibling so keyboard tab order runs Product → the 14 feature links → the rest
 * of the nav, and is positioned absolutely inside the (position: relative,
 * overflow: visible) links wrap. The trigger's original label and href are
 * captured at init and restored by the cleanup, so a teardown leaves the
 * generated markup byte-identical to what the server sent.
 *
 * Link targets: the 14 feature routes below are this menu's own content, but
 * the TRIGGER's href is read from the DOM and restored on teardown — the nav's
 * existing targets are owned by the extractor, not by this file.
 *
 * Desktop only. The export's breakpoints (from the `data-framer-hydrate-v2`
 * payload in shell.tsx) are:
 *   (min-width: 1320px)                          → Desktop
 *   (min-width: 810px) and (max-width: 1319.98px) → Tablet
 *   (max-width: 809.98px)                         → Phone
 * and site.css hides the non-matching `.ssr-variant` wrappers outright, so the
 * whole desktop nav — this panel included — is `display: none` below 1320px.
 * Opening is additionally gated on that same media query, so the panel can
 * never be shown on the tablet/phone nav, which another module owns.
 *
 * Motion is the site's own language, at nav speed: a `bounce: 0` spring, the
 * same family as the 1s scroll reveals in `reveal.tsx` (Framer
 * `{bounce: 0, duration: 1, type: "spring"}`), compressed to 280ms because a
 * nav dropdown must feel instant. `prefers-reduced-motion` shows/hides it with
 * no animation at all.
 */

type Cleanup = () => void;

/* ------------------------------------------------------------------ *
 * Content                                                             *
 * ------------------------------------------------------------------ */

interface FeatureLink {
  /** Rendered uppercase by the stylesheet, like every other nav label. */
  label: string;
  href: string;
  /** One line. Derived from the product, not invented — see `source`. */
  blurb: string;
  /** Where the description came from, for the next person to check. */
  source: string;
}

interface FeatureGroup {
  title: string;
  items: readonly FeatureLink[];
}

const GROUPS: readonly FeatureGroup[] = [
  {
    title: "Create",
    items: [
      {
        label: "Video",
        href: "/features/video",
        blurb:
          "A brief becomes a scripted, voiced, captioned short, posted to TikTok, Reels, and Shorts.",
        source: "app/(marketing)/features/video/page.tsx — DESCRIPTION + hero lede",
      },
      {
        label: "UGC ads",
        href: "/features/ugc",
        blurb:
          "A script plus a few reference images becomes one vertical spokesperson ad.",
        source: "app/(app)/ugc/UgcClient.tsx — studio header",
      },
      {
        label: "Micro-dramas",
        href: "/features/dramas",
        blurb:
          "An idea becomes a screenplay, a locked cast, and a stitched short — one actor throughout.",
        source: "app/(app)/dramas/DramasClient.tsx — page header + file comment",
      },
      {
        label: "Motion graphics",
        href: "/features/motion",
        blurb:
          "Narration becomes timed beats, each with its own b-roll and its own kinetic type.",
        source: "app/(app)/motion/MotionClient.tsx — page header",
      },
      {
        label: "Articles & SEO",
        href: "/features/articles",
        blurb:
          "SERP research, E-E-A-T writing, and QA scoring, with metadata, schema, and links.",
        source: "app/(marketing)/features/articles/page.tsx — DESCRIPTION",
      },
      {
        label: "Templates",
        href: "/features/templates",
        blurb:
          "Curated looks with their exact prompt attached. Remix one with your product photo.",
        source: "app/(app)/templates/TemplatesClient.tsx — DashHeading sub",
      },
    ],
  },
  {
    title: "Distribute",
    items: [
      {
        label: "Ads",
        href: "/features/ads",
        blurb:
          "Create, launch, and scale paid campaigns on Google and Meta behind hard budget guards.",
        source: "app/(app)/ads/AdsOverviewShell.tsx — DashHeading sub",
      },
      {
        label: "Campaigns",
        href: "/features/campaigns",
        blurb:
          "Content, SEO, and ads in one push. Set a budget, set a window, let it run.",
        source: "app/(app)/campaigns/CampaignsClient.tsx — DashHeading sub",
      },
      {
        label: "Scheduling",
        href: "/features/scheduling",
        blurb:
          "One post, every connected platform, each delivery tracked on its own recurring slot.",
        source:
          "app/(app)/scheduled/ScheduledClient.tsx + RecurringSlots.tsx — file header",
      },
      {
        label: "SEO audit",
        href: "/features/seo-audit",
        blurb:
          "Score any page 0-100 on how readable it is to AI answer engines, with the evidence.",
        source: "app/(app)/seo-audit/SeoAuditClient.tsx — PageTitle lede",
      },
    ],
  },
  {
    title: "Control",
    items: [
      {
        label: "Analytics & spend",
        href: "/features/analytics",
        blurb:
          "Views, watch time, and completion feed the next round. Every dollar is metered.",
        source: "app/(marketing)/features/analytics/page.tsx — DESCRIPTION",
      },
      {
        label: "Niches",
        href: "/features/niches",
        blurb:
          "Each niche is its own self-driving pipeline, with its own daily spend cap.",
        source: "app/(app)/niches/page.tsx — DashHeading sub + NichesTable columns",
      },
      {
        label: "Library",
        href: "/features/library",
        blurb:
          "Every video and clip you have produced in one place — play, sort, remix.",
        source: "app/(app)/library/LibraryClient.tsx — DashHeading sub",
      },
      {
        label: "Automation",
        href: "/features/automation",
        blurb:
          "REST API, typed Python SDK, the marketer CLI, and an MCP server, all inside your caps.",
        source: "app/(marketing)/features/automation/page.tsx — DESCRIPTION",
      },
    ],
  },
];

/** The trigger keeps pointing somewhere real: the features overview page. */
const OVERVIEW_HREF = "/features";
const TRIGGER_LABEL = "Product";
/** Case-insensitive match against the anchor the export ships. */
const TRIGGER_MATCH = "features";

/* ------------------------------------------------------------------ *
 * Design tokens — read off the live nav, not chosen                   *
 * ------------------------------------------------------------------ */

/** nav background (`--token-5e3da66b…`). */
const GROUND = "rgb(21, 30, 29)";
/** Card surface used by every panel on the site. */
const SURFACE = "rgb(15, 21, 20)";
/** `--border-color` on the nav and every bordered block. */
const BORDER = "rgb(42, 60, 58)";
/** The nav link colour (`--token-8d29ccb4…`). */
const MUTED = "rgb(129, 152, 149)";
const TEXT = "rgb(252, 253, 253)";
/* Resolves through the brand variable rather than a literal. This panel is
 * injected into the nav, which lives OUTSIDE `#main` — and `bridge.css`
 * re-points the export's accent token only inside `#main`. So a literal
 * here survives a palette change invisibly: the menu is 0x0 while closed,
 * and flashes the old colour the first time someone opens it. The fallback
 * keeps it rendering if the variable is ever absent. */
const ACCENT = "var(--brand-primary, #9ab08d)";
/** Same colour at 6% for hover fills, via color-mix so one source stays. */
const ACCENT_WASH = "color-mix(in srgb, var(--brand-primary, #9ab08d) 6%, transparent)";

/* ------------------------------------------------------------------ *
 * Timing                                                              *
 * ------------------------------------------------------------------ */

const DESKTOP_QUERY = "(min-width: 1320px)";
const REDUCED_QUERY = "(prefers-reduced-motion: reduce)";

/** Hover intent: the pointer must rest on the trigger, not merely cross it. */
const OPEN_DELAY_MS = 90;
/**
 * Close grace. The trigger's text baseline sits 35px above the nav's bottom
 * edge, so a pointer travelling diagonally into the panel is briefly over
 * neither — this is the "safe" window that keeps it open while it crosses.
 */
const CLOSE_DELAY_MS = 160;

/** Same spring family as the scroll reveals, at nav speed. */
const OPEN_SPRING: AnimationOptions = { type: "spring", bounce: 0, duration: 0.28 };
const GROUP_SPRING: AnimationOptions = { type: "spring", bounce: 0, duration: 0.24 };
const GROUP_STAGGER_S = 0.035;
/** Closing is a plain fast tween — nothing should linger on the way out. */
const CLOSE_TWEEN: AnimationOptions = {
  type: "tween",
  duration: 0.12,
  ease: [0.4, 0, 1, 1],
};

/* ------------------------------------------------------------------ *
 * Geometry                                                            *
 * ------------------------------------------------------------------ */

const PANEL_MAX_WIDTH = 900;
const PANEL_PADDING = 16;
/** Minimum gap between the panel and the nav's own left/right edges. */
const PANEL_EDGE_INSET = 24;

const STYLE_ID = "product-menu-style";
const PANEL_ID = "product-menu-panel";

const registry = new WeakMap<HTMLElement, Cleanup>();

const CSS = `
.pm-panel{position:absolute;z-index:30;box-sizing:border-box;
  display:block;padding:${PANEL_PADDING}px;
  background:${SURFACE};color:${TEXT};
  border:1px solid ${BORDER};border-radius:8px;
  box-shadow:0 1px 0 0 rgb(0,0,0),0 24px 60px -24px rgba(0,0,0,.85),0 2px 8px -2px rgba(0,0,0,.5);
  opacity:0;transform:translateY(-8px);will-change:transform,opacity}
.pm-panel[hidden]{display:none}
.pm-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:0}
.pm-group{padding:0 16px;min-width:0}
.pm-group + .pm-group{border-left:1px solid ${BORDER}}
.pm-group:first-child{padding-left:8px}
.pm-group:last-child{padding-right:8px}
.pm-group-title{margin:0 0 10px;padding:0 10px;
  font-family:"JetBrains Mono",monospace;font-size:11px;font-weight:500;
  line-height:16px;letter-spacing:.12em;text-transform:uppercase;color:${ACCENT}}
.pm-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:2px}
.pm-item{display:block;padding:8px 10px;border-radius:4px;text-decoration:none;
  border:1px solid transparent;transition:background-color .12s ease,border-color .12s ease}
.pm-item:hover,.pm-item:focus-visible{background:${ACCENT_WASH};border-color:${BORDER};outline:none}
.pm-item:focus-visible{border-color:${ACCENT}}
.pm-label{display:block;font-family:"JetBrains Mono",monospace;font-size:13px;
  font-weight:500;line-height:18px;letter-spacing:-.13px;text-transform:uppercase;
  color:${TEXT};transition:color .12s ease}
.pm-item:hover .pm-label,.pm-item:focus-visible .pm-label{color:${ACCENT}}
.pm-blurb{display:block;margin-top:3px;
  font-family:"Inter Display","Inter",sans-serif;font-size:12.5px;font-weight:400;
  line-height:17px;color:${MUTED}}
.pm-foot{display:flex;align-items:center;justify-content:space-between;gap:16px;
  margin-top:14px;padding:12px 18px 2px;border-top:1px solid ${BORDER};
  font-family:"JetBrains Mono",monospace;font-size:11px;font-weight:500;
  line-height:16px;letter-spacing:.12em;text-transform:uppercase;color:${MUTED}}
.pm-foot-link{color:${TEXT};text-decoration:none;border-bottom:1px solid ${BORDER};
  padding-bottom:2px;transition:color .12s ease,border-color .12s ease}
.pm-foot-link:hover,.pm-foot-link:focus-visible{color:${ACCENT};border-color:${ACCENT};outline:none}
.pm-caret{display:inline-block;width:8px;height:8px;margin-left:7px;
  vertical-align:1px;color:currentColor}
.pm-caret svg{display:block;width:8px;height:8px}
`;

/* ------------------------------------------------------------------ *
 * Helpers                                                             *
 * ------------------------------------------------------------------ */

function matches(query: string): boolean {
  return (
    typeof window !== "undefined" &&
    typeof window.matchMedia === "function" &&
    window.matchMedia(query).matches
  );
}

function svgCaret(): SVGSVGElement {
  const ns = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(ns, "svg");
  svg.setAttribute("viewBox", "0 0 8 8");
  svg.setAttribute("fill", "none");
  svg.setAttribute("aria-hidden", "true");
  const path = document.createElementNS(ns, "path");
  path.setAttribute("d", "M1 2.75 4 5.5l3-2.75");
  path.setAttribute("stroke", "currentColor");
  path.setAttribute("stroke-width", "1.2");
  path.setAttribute("stroke-linecap", "square");
  svg.appendChild(path);
  return svg;
}

/* ------------------------------------------------------------------ */

export function initProductMenu(root: HTMLElement): Cleanup | void {
  if (typeof window === "undefined") return;

  const existing = registry.get(root);
  if (existing) return existing;

  // The desktop nav specifically — the Tablet/Phone variants are another
  // module's territory and are `display: none` here anyway.
  const nav = root.querySelector<HTMLElement>('nav[data-framer-name="Desktop"]');
  if (!nav) return;

  const host =
    nav.querySelector<HTMLElement>('[data-framer-name="Nav Links Wrap"]') ?? null;
  if (!host) return;

  const trigger =
    Array.from(host.querySelectorAll("a")).find(
      (a) => (a.textContent ?? "").trim().toLowerCase() === TRIGGER_MATCH,
    ) ?? null;
  if (!trigger) return;

  const triggerWrap =
    trigger.closest<HTMLElement>('[data-framer-name="Text Button"]') ?? trigger;

  // Defensive: a hot reload that skipped the cleanup would otherwise stack
  // panels. The registry already covers StrictMode's mount/unmount/mount.
  for (const stale of Array.from(document.querySelectorAll(".pm-panel"))) {
    stale.remove();
  }

  /* -- trigger ---------------------------------------------------- */

  const originalLabel = trigger.textContent ?? "";
  const originalHref = trigger.getAttribute("href");

  trigger.textContent = TRIGGER_LABEL;
  trigger.setAttribute("href", OVERVIEW_HREF);
  trigger.setAttribute("aria-haspopup", "true");
  trigger.setAttribute("aria-expanded", "false");
  trigger.setAttribute("aria-controls", PANEL_ID);

  const caret = document.createElement("span");
  caret.className = "pm-caret";
  caret.setAttribute("aria-hidden", "true");
  caret.appendChild(svgCaret());
  trigger.appendChild(caret);

  /* -- stylesheet ------------------------------------------------- */

  let style = document.getElementById(STYLE_ID) as HTMLStyleElement | null;
  const ownsStyle = style === null;
  if (!style) {
    style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent = CSS;
    document.head.appendChild(style);
  }

  /* -- panel ------------------------------------------------------ */

  const panel = document.createElement("div");
  panel.className = "pm-panel";
  panel.id = PANEL_ID;
  panel.hidden = true;
  // A landmark with a name: screen readers announce "Product, navigation".
  panel.setAttribute("role", "navigation");
  panel.setAttribute("aria-label", TRIGGER_LABEL);

  const grid = document.createElement("div");
  grid.className = "pm-grid";
  panel.appendChild(grid);

  const columns: HTMLAnchorElement[][] = [];
  const groupEls: HTMLElement[] = [];

  for (const group of GROUPS) {
    const column = document.createElement("div");
    column.className = "pm-group";

    const heading = document.createElement("p");
    heading.className = "pm-group-title";
    heading.id = `${PANEL_ID}-${group.title.toLowerCase()}`;
    heading.textContent = group.title;
    column.appendChild(heading);

    const list = document.createElement("ul");
    list.className = "pm-list";
    list.setAttribute("aria-labelledby", heading.id);

    const anchors: HTMLAnchorElement[] = [];
    for (const item of group.items) {
      const li = document.createElement("li");
      const link = document.createElement("a");
      link.className = "pm-item";
      link.href = item.href;

      const label = document.createElement("span");
      label.className = "pm-label";
      label.textContent = item.label;

      const blurb = document.createElement("span");
      blurb.className = "pm-blurb";
      blurb.textContent = item.blurb;

      link.append(label, blurb);
      li.appendChild(link);
      list.appendChild(li);
      anchors.push(link);
    }

    column.appendChild(list);
    grid.appendChild(column);
    columns.push(anchors);
    groupEls.push(column);
  }

  const foot = document.createElement("div");
  foot.className = "pm-foot";
  const footNote = document.createElement("span");
  footNote.textContent = "One brief in. Every channel out.";
  const footLink = document.createElement("a");
  footLink.className = "pm-foot-link";
  footLink.href = OVERVIEW_HREF;
  footLink.textContent = "All features";
  foot.append(footNote, footLink);
  panel.appendChild(foot);

  triggerWrap.insertAdjacentElement("afterend", panel);

  const items = columns.flat();
  const focusables: HTMLAnchorElement[] = [...items, footLink];

  /* -- state ------------------------------------------------------ */

  const controller = new AbortController();
  const { signal } = controller;
  const desktop = window.matchMedia(DESKTOP_QUERY);

  let open = false;
  let openTimer = 0;
  let closeTimer = 0;
  const running: { stop: () => void }[] = [];

  const clearTimers = () => {
    window.clearTimeout(openTimer);
    window.clearTimeout(closeTimer);
    openTimer = 0;
    closeTimer = 0;
  };

  const stopAnimations = () => {
    for (const controls of running) controls.stop();
    running.length = 0;
  };

  /** Anchor the panel under the trigger, clamped inside the nav's width. */
  const place = () => {
    const navRect = nav.getBoundingClientRect();
    const hostRect = host.getBoundingClientRect();
    const wrapRect = triggerWrap.getBoundingClientRect();

    const width = Math.min(PANEL_MAX_WIDTH, navRect.width - PANEL_EDGE_INSET * 2);
    const minLeft = navRect.left + PANEL_EDGE_INSET;
    const maxLeft = navRect.right - PANEL_EDGE_INSET - width;
    const wanted = wrapRect.left - PANEL_PADDING;
    const left = Math.min(Math.max(wanted, minLeft), Math.max(minLeft, maxLeft));

    panel.style.width = `${Math.round(width)}px`;
    panel.style.left = `${Math.round(left - hostRect.left)}px`;
    // Flush with the nav's 1px bottom border, so the two hairlines merge.
    panel.style.top = `${Math.round(navRect.bottom - 1 - hostRect.top)}px`;
  };

  const doOpen = (focusFirst = false) => {
    clearTimers();
    if (!desktop.matches) return;
    if (open) {
      if (focusFirst) items[0]?.focus();
      return;
    }
    open = true;
    trigger.setAttribute("aria-expanded", "true");
    panel.hidden = false;
    place();
    stopAnimations();

    if (matches(REDUCED_QUERY)) {
      panel.style.opacity = "1";
      panel.style.transform = "none";
      for (const el of groupEls) {
        el.style.opacity = "1";
        el.style.transform = "none";
      }
      caret.style.transform = "rotate(180deg)";
    } else {
      running.push(animate(panel, { opacity: [0, 1], y: [-8, 0] }, OPEN_SPRING));
      groupEls.forEach((el, index) => {
        running.push(
          animate(
            el,
            { opacity: [0, 1], y: [6, 0] },
            { ...GROUP_SPRING, delay: index * GROUP_STAGGER_S },
          ),
        );
      });
      running.push(animate(caret, { rotate: 180 }, OPEN_SPRING));
    }

    if (focusFirst) items[0]?.focus();
  };

  const doClose = (restoreFocus = false) => {
    clearTimers();
    if (!open) {
      if (restoreFocus) trigger.focus();
      return;
    }
    open = false;
    trigger.setAttribute("aria-expanded", "false");
    stopAnimations();

    if (matches(REDUCED_QUERY)) {
      panel.hidden = true;
      caret.style.transform = "none";
    } else {
      running.push(
        animate(panel, { opacity: 0, y: -6 }, {
          ...CLOSE_TWEEN,
          onComplete: () => {
            // A reopen during the fade must win.
            if (!open) panel.hidden = true;
          },
        }),
      );
      running.push(animate(caret, { rotate: 0 }, CLOSE_TWEEN));
    }

    if (restoreFocus) trigger.focus();
  };

  const scheduleOpen = () => {
    window.clearTimeout(closeTimer);
    closeTimer = 0;
    if (open || openTimer) return;
    openTimer = window.setTimeout(() => {
      openTimer = 0;
      doOpen();
    }, OPEN_DELAY_MS);
  };

  const scheduleClose = () => {
    window.clearTimeout(openTimer);
    openTimer = 0;
    if (!open || closeTimer) return;
    closeTimer = window.setTimeout(() => {
      closeTimer = 0;
      doClose();
    }, CLOSE_DELAY_MS);
  };

  /* -- pointer ---------------------------------------------------- */

  triggerWrap.addEventListener("pointerenter", scheduleOpen, { signal });
  triggerWrap.addEventListener("pointerleave", scheduleClose, { signal });
  panel.addEventListener(
    "pointerenter",
    () => {
      window.clearTimeout(closeTimer);
      closeTimer = 0;
    },
    { signal },
  );
  panel.addEventListener("pointerleave", scheduleClose, { signal });

  trigger.addEventListener(
    "click",
    (event) => {
      // Let the browser handle "open in new tab/window" and middle clicks.
      if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
      if (!desktop.matches) return;
      event.preventDefault();
      if (open) doClose();
      else doOpen();
    },
    { signal },
  );

  /* -- keyboard --------------------------------------------------- */

  trigger.addEventListener(
    "keydown",
    (event) => {
      if (!desktop.matches) return;
      const key = event.key;
      if (key === "Enter" || key === " " || key === "Spacebar") {
        event.preventDefault();
        if (open) doClose();
        else doOpen(true);
      } else if (key === "ArrowDown") {
        event.preventDefault();
        doOpen(true);
      } else if (key === "Escape" && open) {
        event.preventDefault();
        doClose();
      }
    },
    { signal },
  );

  const focusAt = (index: number) => {
    const target = focusables[(index + focusables.length) % focusables.length];
    target?.focus();
  };

  panel.addEventListener(
    "keydown",
    (event) => {
      const active = document.activeElement as HTMLAnchorElement | null;
      const index = active ? focusables.indexOf(active) : -1;

      switch (event.key) {
        case "Escape":
          event.preventDefault();
          doClose(true);
          return;
        case "ArrowDown":
          event.preventDefault();
          focusAt(index + 1);
          return;
        case "ArrowUp":
          event.preventDefault();
          if (index <= 0) {
            trigger.focus();
            return;
          }
          focusAt(index - 1);
          return;
        case "Home":
          event.preventDefault();
          focusAt(0);
          return;
        case "End":
          event.preventDefault();
          focusAt(focusables.length - 1);
          return;
        case "ArrowRight":
        case "ArrowLeft": {
          // Column-wise movement, holding the row where one exists.
          const column = columns.findIndex((c) => active && c.includes(active));
          if (column === -1) return;
          event.preventDefault();
          const row = columns[column].indexOf(active as HTMLAnchorElement);
          const step = event.key === "ArrowRight" ? 1 : -1;
          const next = (column + step + columns.length) % columns.length;
          const target = columns[next];
          target[Math.min(row, target.length - 1)]?.focus();
          return;
        }
        default:
      }
    },
    { signal },
  );

  /* -- dismissal -------------------------------------------------- */

  // Blur-out: focus left both the trigger and the panel.
  nav.addEventListener(
    "focusout",
    (event) => {
      if (!open) return;
      const next = event.relatedTarget as Node | null;
      if (next && (panel.contains(next) || trigger.contains(next) || next === trigger)) {
        return;
      }
      doClose();
    },
    { signal },
  );

  document.addEventListener(
    "pointerdown",
    (event) => {
      if (!open) return;
      const target = event.target as Node | null;
      if (target && (panel.contains(target) || triggerWrap.contains(target))) return;
      doClose();
    },
    { signal, capture: true },
  );

  document.addEventListener(
    "keydown",
    (event) => {
      if (open && event.key === "Escape") doClose(true);
    },
    { signal },
  );

  // Route change. The marketing layout keeps this module mounted across
  // client navigations, so nothing else would tear the panel down: any
  // anchor activation (Next's <Link> renders one) and any history move
  // closes it.
  document.addEventListener(
    "click",
    (event) => {
      if (!open) return;
      const target = event.target as Element | null;
      const anchor = target?.closest?.("a[href]");
      if (!anchor || anchor === trigger) return;
      doClose();
    },
    { signal, capture: true },
  );
  window.addEventListener("popstate", () => doClose(), { signal });
  window.addEventListener("hashchange", () => doClose(), { signal });

  /* -- viewport --------------------------------------------------- */

  const onBreakpoint = () => {
    if (!desktop.matches && open) {
      clearTimers();
      stopAnimations();
      open = false;
      trigger.setAttribute("aria-expanded", "false");
      panel.hidden = true;
      caret.style.transform = "none";
    }
  };
  desktop.addEventListener("change", onBreakpoint, { signal });

  let resizeFrame = 0;
  window.addEventListener(
    "resize",
    () => {
      if (!open) return;
      cancelAnimationFrame(resizeFrame);
      resizeFrame = requestAnimationFrame(place);
    },
    { signal },
  );

  /* -- teardown --------------------------------------------------- */

  const cleanup: Cleanup = () => {
    if (registry.get(root) !== cleanup) return;
    registry.delete(root);

    clearTimers();
    stopAnimations();
    cancelAnimationFrame(resizeFrame);
    controller.abort();

    panel.remove();
    caret.remove();
    if (ownsStyle) style?.remove();

    trigger.textContent = originalLabel;
    if (originalHref === null) trigger.removeAttribute("href");
    else trigger.setAttribute("href", originalHref);
    trigger.removeAttribute("aria-haspopup");
    trigger.removeAttribute("aria-expanded");
    trigger.removeAttribute("aria-controls");
  };

  registry.set(root, cleanup);
  return cleanup;
}
