"""Parsing-layer port fidelity for the SEO auditor.

Every expectation here was generated by running the TypeScript original
(`ai-seo-audit/lib/audit.ts`) over the same input and recording what it
produced, so these are parity assertions against the source of truth rather
than a snapshot of whatever the Python happens to do today.

The parsing layer is where a regex port diverges silently: JS `RegExp` and
Python `re` disagree about `$`, about Unicode classes, and about how
alternation interacts with `findall` capture groups. The cases below target
exactly those seams.
"""
from __future__ import annotations

import pytest

from marketer.seoaudit import parsing
from marketer.seoaudit.parsing import Heading, SchemaSummary
from marketer.seoaudit.types import AuditStatus

# ---------------------------------------------------------------------------
# Attribute reading: the `href` vs `data-href` boundary
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("tag", "attr", "expected"),
    [
        # The whole point of the leading-boundary assertion: `data-href` must
        # not satisfy a request for `href`.
        ('<a data-href="/decoy" href="/real">', "href", "/real"),
        ('<a data-href="/decoy">', "href", None),
        ('<a xhref="/no">', "href", None),
        ('<link data-rel="canonical" rel="canonical" href="/c">', "rel", "canonical"),
        # Quoting and spacing variants the source accepts.
        ("<a href='/single'>", "href", "/single"),
        ("<a href=/unquoted class=x>", "href", "/unquoted"),
        ('<a HREF="/upper">', "href", "/upper"),
        ('<a href = "/spaced">', "href", "/spaced"),
        # Attribute values ARE entity-decoded (unlike script bodies).
        ('<a href="/q?a=1&amp;b=2">', "href", "/q?a=1&b=2"),
    ],
)
def test_get_attr_requires_an_attribute_boundary(tag, attr, expected):
    assert parsing.get_attr(tag, attr) == expected


# ---------------------------------------------------------------------------
# Head metadata
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("html", "expected"),
    [
        ('<link rel="canonical" href="https://x.example/a">', "https://x.example/a"),
        ("<link rel='CANONICAL' href='https://x.example/b'>", "https://x.example/b"),
        # `rel` is a space-separated token list, so "canonical nofollow" counts.
        ('<link rel="canonical nofollow" href="https://x.example/c">', "https://x.example/c"),
        ("<link rel=canonical href=/unquoted>", "/unquoted"),
        # ...but `data-rel` must not be mistaken for `rel`.
        ('<link data-rel="canonical" href="https://x.example/d">', None),
        ('<link rel="alternate" href="/x"><link rel="canonical" href="/y">', "/y"),
        ("<p>nothing</p>", None),
    ],
)
def test_extract_canonical(html, expected):
    assert parsing.extract_canonical(html) == expected


@pytest.mark.parametrize(
    ("html", "expected"),
    [
        ('<meta name="robots" content="noindex, nofollow">', True),
        ('<meta name="ROBOTS" content="NOINDEX">', True),
        ('<meta name="googlebot" content="noindex">', True),
        ('<meta property="robots" content="noindex">', True),
        ('<meta name="robots" content="index,follow">', False),
        # `\bnoindex\b` must not fire on a longer word...
        ('<meta name="robots" content="noindexing">', False),
        # ...nor on an unrelated meta tag that merely mentions the word...
        ('<meta name="description" content="noindex is a word">', False),
        # ...nor on body copy.
        ("<p>noindex</p>", False),
    ],
)
def test_detect_noindex(html, expected):
    assert parsing.detect_noindex(html) is expected


@pytest.mark.parametrize(
    ("html", "expected"),
    [
        ("<title>Hello &amp; goodbye</title>", "Hello & goodbye"),
        ('<TITLE data-x="1">  Spaced\n  Out </TITLE>', "Spaced Out"),
        ("<title></title>", ""),
        ("<titlex>no</titlex>", None),
    ],
)
def test_extract_title(html, expected):
    assert parsing.extract_title(html) == expected


@pytest.mark.parametrize(
    ("html", "expected"),
    [
        ('<meta name="description" content="D &amp; E">', "D & E"),
        # `property=` is accepted as a fallback for `name=`.
        ('<meta property="description" content="prop">', "prop"),
        ('<meta name="DESCRIPTION" content="upper">', "upper"),
        # An empty content attribute does not win; the scan continues.
        (
            '<meta name="description" content=""><meta name="description" content="second">',
            "second",
        ),
        ('<meta name="other" content="x">', None),
    ],
)
def test_extract_meta_content(html, expected):
    assert parsing.extract_meta_content(html, "description") == expected


# ---------------------------------------------------------------------------
# JSON-LD: wrappers, parse order, @graph, and script-tag matching
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("html", "types"),
    [
        ('<script type="application/ld+json">{"@type":"Organization"}</script>', ["Organization"]),
        # Odd spacing around `=` plus single quotes.
        ("<script type = 'application/ld+json'>{\"@type\":\"Person\"}</script>", ["Person"]),
        # Unquoted attribute value.
        ('<script type=application/ld+json>{"@type":"Product"}</script>', ["Product"]),
        # Extra attributes on either side of `type`.
        (
            '<script id="x" type="application/ld+json" data-y="1">{"@type":"Service"}</script>',
            ["Service"],
        ),
        ('<script type="APPLICATION/LD+JSON">{"@type":"Offer"}</script>', ["Offer"]),
        ('<script type=" application/ld+json ">{"@type":"Spaced"}</script>', ["Spaced"]),
        # A non-JSON-LD script must not match at all.
        ('<script type="text/javascript">{"@type":"Nope"}</script>', []),
    ],
)
def test_extract_json_ld_script_tag_matching(html, types):
    blocks = parsing.extract_json_ld(html)
    assert [s.get("@type") for s in blocks.schemas] == types


@pytest.mark.parametrize(
    ("body", "expected_type"),
    [
        ('<!-- {"@type":"Commented"} -->', "Commented"),
        ('//<![CDATA[\n{"@type":"Cdata"}\n//]]>', "Cdata"),
        ('/*<![CDATA[*/{"@type":"BlockCdata"}/*]]>*/', "BlockCdata"),
        ('// <![CDATA[ {"@type":"SpacedCdata"} // ]]>', "SpacedCdata"),
    ],
)
def test_extract_json_ld_strips_cms_wrappers(body, expected_type):
    """Comment and CDATA wrappers that CMSs inject are peeled before parsing."""
    html = f'<script type="application/ld+json">{body}</script>'
    blocks = parsing.extract_json_ld(html)
    assert [s["@type"] for s in blocks.schemas] == [expected_type]
    assert blocks.parse_failures == 0


def test_json_ld_is_parsed_raw_before_html_decoding():
    """`&amp;` inside a query string must survive.

    Browsers do not entity-decode `<script>` bodies, so the source parses the
    raw text first and only retries a decoded copy when the raw parse fails.
    Decoding first would silently rewrite `?b=1&amp;c=2` to `?b=1&c=2` — still
    valid JSON, so the corruption would never surface as a parse error.
    """
    html = (
        '<script type="application/ld+json">'
        '{"@type":"WebPage","url":"https://x.example/a?b=1&amp;c=2"}'
        "</script>"
    )
    blocks = parsing.extract_json_ld(html)
    assert blocks.schemas[0]["url"] == "https://x.example/a?b=1&amp;c=2"


def test_json_ld_falls_back_to_a_decoded_parse():
    """Publishers who (incorrectly) entity-encode their JSON-LD still parse."""
    html = (
        '<script type="application/ld+json">'
        "{&quot;@type&quot;:&quot;Encoded&quot;}"
        "</script>"
    )
    blocks = parsing.extract_json_ld(html)
    assert [s["@type"] for s in blocks.schemas] == ["Encoded"]
    assert blocks.parse_failures == 0


def test_json_ld_flattens_graph_keeping_the_wrapper():
    """`@graph` nodes are hoisted alongside — not instead of — their wrapper."""
    html = (
        '<script type="application/ld+json">'
        '{"@context":"x","@graph":[{"@type":"Organization"},{"@type":"Person"}]}'
        "</script>"
    )
    blocks = parsing.extract_json_ld(html)
    assert [s.get("@type") for s in blocks.schemas] == [None, "Organization", "Person"]
    assert blocks.schemas[0]["@context"] == "x"


def test_json_ld_flattens_top_level_arrays():
    html = '<script type="application/ld+json">[{"@type":"A"},{"@type":"B"}]</script>'
    assert [s["@type"] for s in parsing.extract_json_ld(html).schemas] == ["A", "B"]


def test_json_ld_ignores_a_non_list_graph():
    html = '<script type="application/ld+json">{"@graph":"notalist"}</script>'
    blocks = parsing.extract_json_ld(html)
    assert blocks.schemas == [{"@graph": "notalist"}]


@pytest.mark.parametrize(
    ("body", "schemas", "blocks_found", "failures"),
    [
        ("not json{", 0, 1, 1),
        # Whitespace-only blocks are counted as blocks but are not failures.
        ("   ", 0, 1, 0),
        # Valid JSON that isn't an object contributes no entities, no failure.
        ("null", 0, 1, 0),
        ('"juststring"', 0, 1, 0),
    ],
)
def test_extract_json_ld_counts_blocks_and_failures(body, schemas, blocks_found, failures):
    html = f'<script type="application/ld+json">{body}</script>'
    result = parsing.extract_json_ld(html)
    assert len(result.schemas) == schemas
    assert result.block_count == blocks_found
    assert result.parse_failures == failures


def test_extract_json_ld_counts_each_block_separately():
    html = (
        '<script type="application/ld+json">{"a":1}</script>'
        '<script type="application/ld+json">bad</script>'
    )
    result = parsing.extract_json_ld(html)
    assert (len(result.schemas), result.block_count, result.parse_failures) == (1, 2, 1)


def test_summarize_schema_reads_types_arrays_and_same_as():
    summary = parsing.summarize_schema(
        [
            {
                "@type": ["Organization", "Thing"],
                "name": "A",
                "url": "u",
                "logo": "l",
                "sameAs": "one-string-not-a-list",
            },
            {"@type": "BlogPosting", "headline": "h", "author": "a",
             "datePublished": "d", "dateModified": "m"},
            {"@type": "Person", "sameAs": ["x", "y"]},
            {"@type": "FAQPage"},
        ]
    )
    assert summary.has_organization is True
    assert summary.organization_complete is True
    assert summary.has_article is True
    assert summary.article_complete is True
    assert summary.has_person is True
    assert summary.has_author is True
    assert summary.has_faq is True
    # A bare string sameAs counts as one; sameAs is summed across ALL entities.
    assert summary.same_as_count == 3


def test_organization_is_incomplete_without_same_as():
    summary = parsing.summarize_schema(
        [{"@type": "Organization", "name": "A", "url": "u", "logo": "l"}]
    )
    assert summary.has_organization is True
    assert summary.organization_complete is False
    assert summary.organization_evidence == (
        "Organization-like schema found; complete core fields: no; sameAs links: 0."
    )


def test_summarize_schema_on_nothing():
    summary = parsing.summarize_schema([])
    assert summary.organization_evidence == "No Organization-like schema was found."
    assert summary.article_evidence == "No Article or BlogPosting schema was found."
    assert summary.same_as_count == 0


# ---------------------------------------------------------------------------
# Links
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("html", "markdown", "base", "expected"),
    [
        (
            '<a href="/a">x</a><a href="https://other.example/b">y</a>',
            "",
            "https://acme.example/p/",
            ["https://acme.example/a", "https://other.example/b"],
        ),
        # Non-web schemes are dropped.
        (
            '<a href="mailto:x@y.com">m</a><a href="tel:+1">t</a>'
            '<a href="javascript:void(0)">j</a>',
            "",
            "https://acme.example/",
            [],
        ),
        # Fragments are stripped, which also collapses "#" to the base URL.
        ('<a href="/a#frag">x</a>', "", "https://acme.example/", ["https://acme.example/a"]),
        (
            '<a href="">empty</a><a href="#">hash</a>',
            "",
            "https://acme.example/",
            ["https://acme.example/"],
        ),
        # Duplicates collapse, insertion order is preserved.
        ('<a href="/dup">1</a><a href="/dup">2</a>', "", "https://acme.example/",
         ["https://acme.example/dup"]),
        # Markdown link syntax contributes too.
        (
            "",
            "[link](https://md.example/x) and [two](https://md.example/y)",
            "https://acme.example/",
            ["https://md.example/x", "https://md.example/y"],
        ),
        # `data-href` is not a link.
        ('<a data-href="/decoy">no</a>', "", "https://acme.example/", []),
        # Default ports are dropped, matching `new URL().toString()`.
        (
            '<a href="https://acme.example:443/ssl">p</a>',
            "",
            "https://acme.example/",
            ["https://acme.example/ssl"],
        ),
        # A bare origin serializes with a trailing slash.
        ('<a href="https://acme.example">bare</a>', "", "https://acme.example/",
         ["https://acme.example/"]),
        # Protocol-relative hrefs inherit the base scheme.
        ('<a href="//cdn.example/x">p</a>', "", "https://acme.example/",
         ["https://cdn.example/x"]),
        # Query-only hrefs resolve against the base path.
        ('<a href="?q=1">rel</a>', "", "https://acme.example/page",
         ["https://acme.example/page?q=1"]),
    ],
)
def test_extract_links(html, markdown, base, expected):
    assert parsing.extract_links(html, markdown, base) == expected


def test_url_origin_ignores_case_and_path():
    assert parsing.url_origin("HTTPS://Acme.Example/deep/path?q=1") == "https://acme.example"


# ---------------------------------------------------------------------------
# Headings and paragraphs
# ---------------------------------------------------------------------------


def test_extract_headings_merges_html_and_markdown_views():
    headings = parsing.extract_headings(
        '<h1>One</h1><h2 class="x">Two</h2>', "# One\n## Two\n### Three"
    )
    assert [(h.level, h.text) for h in headings] == [(1, "One"), (2, "Two"), (3, "Three")]


def test_extract_headings_dedupes_case_insensitively_within_a_level():
    headings = parsing.extract_headings("<h1>Case</h1>", "# case")
    assert [(h.level, h.text) for h in headings] == [(1, "Case")]


def test_extract_headings_keeps_same_text_at_different_levels():
    headings = parsing.extract_headings("<h1>Same</h1><h2>Same</h2>", "")
    assert [(h.level, h.text) for h in headings] == [(1, "Same"), (2, "Same")]


def test_extract_headings_drops_empty_text_and_unwraps_inner_tags():
    headings = parsing.extract_headings(
        "<h1></h1><h2>Outer <span>inner</span></h2><h3>A &amp; B</h3>", ""
    )
    assert [(h.level, h.text) for h in headings] == [(2, "Outer inner"), (3, "A & B")]


def test_extract_headings_requires_a_space_after_markdown_hashes():
    headings = parsing.extract_headings("", "# Real\n#NoSpace")
    assert [h.text for h in headings] == ["Real"]


def test_extract_paragraphs_splits_on_blank_lines_and_drops_short_blocks():
    paragraphs = parsing.extract_paragraphs(
        "Short one.\n\n"
        "This paragraph has more than eight words in it for sure.\n\n"
        "- bullet item with enough words to count here\n"
    )
    assert paragraphs == [
        "This paragraph has more than eight words in it for sure.",
        "bullet item with enough words to count here",
    ]


def test_extract_paragraphs_strips_fenced_code_and_markdown_syntax():
    paragraphs = parsing.extract_paragraphs(
        "```\ncode block with plenty of words inside of it\n```\n\n"
        "# Heading with enough words to count as a paragraph here\n\n"
        "[anchor text here](https://x.example/target) plus more words to reach eight\n"
    )
    assert paragraphs == [
        "Heading with enough words to count as a paragraph here",
        # Markdown links collapse to their target, not their label.
        "https://x.example/target plus more words to reach eight",
    ]


# ---------------------------------------------------------------------------
# Data points, dates, FAQ, byline
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        # 2024 + 30% + $1,200,000 + 2.5x  -> 4
        ("In 2024 revenue grew 30% to $1,200,000, a 2.5x increase.", 4),
        ("No numbers here at all.", 0),
        # Only 19xx/20xx years count as year-shaped.
        ("1999 and 2001 and 1899", 2),
        ("$ 40 and 12.5% and 3x", 3),
        ("1,000,000 and 12,345.67", 2),
    ],
)
def test_count_data_points(text, expected):
    assert parsing.count_data_points(text) == expected


@pytest.mark.parametrize(
    ("html", "text", "schemas", "any_date", "modified"),
    [
        ('<time datetime="2024-01-01">x</time>', "text", [], True, False),
        # A bare <time> tag still counts as a date signal.
        ("<time>x</time>", "text", [], True, False),
        ("", "nothing", [{"dateModified": "2024-01-01"}], True, True),
        ("", "nothing", [{}], False, False),
        ("", "Published Jan 5, 2024", [], True, False),
        ("", "Sept. 12 2023", [], True, False),
        ("", "2024-01-05", [], True, False),
        # "modified" is a stronger signal than "any date" and does not imply it:
        # a visible updated-date phrase sets has_modified_date without matching
        # any of the absolute-date shapes. Faithful to the source.
        ("", "Last updated March 2024 by us", [], False, True),
    ],
)
def test_extract_date_signals(html, text, schemas, any_date, modified):
    signals = parsing.extract_date_signals(html, text, schemas)
    assert signals.has_any_date is any_date
    assert signals.has_modified_date is modified


def test_date_signal_evidence_string():
    signals = parsing.extract_date_signals(
        '<time datetime="2024-01-01">x</time>', "Updated in 2024", [{"dateModified": "z"}]
    )
    assert signals.evidence == (
        "dateModified schema: yes; visible modified date: yes; time tag: yes."
    )


@pytest.mark.parametrize(
    ("text", "headings", "expected"),
    [
        ("Our FAQ section", [], AuditStatus.passed),
        ("Frequently asked questions below", [], AuditStatus.passed),
        ("questions and answers here", [], AuditStatus.passed),
        # Two question-style headings are enough on their own.
        ("nothing", [(2, "What is this?"), (2, "How much?")], AuditStatus.passed),
        ("nothing", [(2, "Only one?")], AuditStatus.partial),
        ("Is this a question? And another? Yes.", [], AuditStatus.partial),
        ("Just one question? yes", [], AuditStatus.fail),
        ("plain text", [], AuditStatus.fail),
        # `\bfaq\b` does not match "faqs".
        ("faqs plural", [], AuditStatus.fail),
    ],
)
def test_compute_faq_status(text, headings, expected):
    status = parsing.compute_faq_status(text, [Heading(lvl, txt) for lvl, txt in headings])
    assert status is expected


@pytest.mark.parametrize(
    ("text", "has_person", "has_author", "expected"),
    [
        ("Written by Dana Ruiz on Tuesday", False, False, True),
        ("Reviewed by Sam O'Neill-Smith", False, False, True),
        # Capitalisation of the NAME is the signal, so a lowercase name loses.
        ("by dana ruiz", False, False, False),
        # The whole pattern is case-sensitive, including the cue word: a
        # sentence-initial "By" does not match, only a mid-sentence "by".
        ("By Dana", False, False, False),
        ("A post by Dana", False, False, True),
        # The name token needs 2+ characters, so bare initials do not match.
        ("Edited by A B C D E F", False, False, False),
        ("Edited by Al Bo", False, False, True),
        # Schema authorship short-circuits the text scan.
        ("no byline at all", True, False, True),
        ("no byline at all", False, True, True),
        ("no byline at all", False, False, False),
    ],
)
def test_detect_byline(text, has_person, has_author, expected):
    schema = SchemaSummary(has_person=has_person, has_author=has_author)
    assert parsing.detect_byline(text, schema) is expected


# ---------------------------------------------------------------------------
# Text normalization
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("a &amp; b", "a & b"),
        # Order is load-bearing: `&amp;` expands first, so `&amp;lt;` -> `<`.
        ("&amp;lt;", "<"),
        # A single decoding pass only, so "&amp;amp;" lands on "&amp;".
        ("&amp;amp;", "&amp;"),
        ("&nbsp;x", " x"),
        ("&quot;q&quot;", '"q"'),
        ("&#39;s", "'s"),
        ("&lt;tag&gt;", "<tag>"),
    ],
)
def test_decode_html(raw, expected):
    assert parsing.decode_html(raw) == expected


@pytest.mark.parametrize(
    ("html", "expected"),
    [
        ("<p>Hello <b>world</b></p>", "Hello world"),
        # Script/style/noscript bodies are removed, not just their tags.
        ("<script>var x = 1;</script><p>After</p>", "After"),
        ("<style>.a{}</style><p>B</p>", "B"),
        ("<noscript>NS</noscript><p>C</p>", "C"),
        ("<p>A &amp; B</p>", "A & B"),
        # HTML comments are stripped by the generic tag regex.
        ("<!-- comment --><p>D</p>", "D"),
    ],
)
def test_html_to_text(html, expected):
    assert parsing.html_to_text(html) == expected


@pytest.mark.parametrize(
    ("raw", "expected"), [("  a \n\t b  ", "a b"), ("", ""), (" x", "x")]
)
def test_normalize_whitespace(raw, expected):
    assert parsing.normalize_whitespace(raw) == expected


# ---------------------------------------------------------------------------
# Word counting: Latin + CJK
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        ("hello world", 2),
        ("", 0),
        # Apostrophes and hyphens stay inside a token.
        ("don't stop", 2),
        ("well-known", 1),
        # Latin-1 / Latin Extended letters are word characters.
        ("café naïve", 2),
        ("a1 b2", 2),
        # Separators split numbers, because the character class excludes
        # "," and "." — this is the source's documented regex fallback.
        ("4,200 queries", 3),
        # CJK is counted per character and added to the Latin token count.
        ("日本語 test", 4),
        ("日本語のテキスト", 8),
    ],
)
def test_count_words(text, expected):
    assert parsing.count_words(text) == expected


# ---------------------------------------------------------------------------
# Readability
# ---------------------------------------------------------------------------

_ENGLISH = (
    "The retrieval layer decides which documents reach the model, and that "
    "single decision drives most of the answer quality you will ever measure. "
    "A weak retriever cannot be rescued by a strong generator. We compared "
    "twelve stacks under identical conditions and recorded the median result "
    "of three separate runs. The corpus was fixed, the embedding model was "
    "fixed, and only the retrieval strategy changed between runs. Reranking "
    "improved precision on long questions but added latency everywhere. "
    "Short factual questions were often made worse by the extra stage. "
    "Teams should measure both cases before adopting a reranker."
)

_CJK = "検索拡張生成は、問い合わせ時に取得した文書に言語モデルを根拠づける技術です。" * 6


def test_flesch_kincaid_returns_a_grade_for_english_prose():
    grade = parsing.flesch_kincaid_grade(_ENGLISH)
    assert grade is not None
    assert 6 < grade < 20


def test_flesch_kincaid_bails_out_on_cjk_heavy_text():
    """Flesch-Kincaid is English-specific, so CJK text must yield None
    rather than a confident nonsense grade."""
    assert parsing.cjk_ratio(_CJK) > 0.35
    assert parsing.flesch_kincaid_grade(_CJK) is None


def test_flesch_kincaid_bails_out_on_short_text():
    assert parsing.flesch_kincaid_grade("Short text. Another one. And a third.") is None


def test_flesch_kincaid_bails_out_on_too_few_sentences():
    # Plenty of words, but only two sentence terminators.
    text = " ".join(["word"] * 100) + ". More words here. "
    assert parsing.flesch_kincaid_grade(text) is None


@pytest.mark.parametrize(
    ("text", "expected"),
    # The denominator is the raw character count, not the token count.
    [("", 0.0), ("abc", 0.0), ("日本語", 1.0), ("abc日本語def", 1 / 3)],
)
def test_cjk_ratio(text, expected):
    assert parsing.cjk_ratio(text) == pytest.approx(expected)


@pytest.mark.parametrize(
    ("word", "expected"),
    [
        ("hello", 2),
        # Vowel GROUPS, not vowels: "b-eau-t-i-f-u-l" is three groups.
        ("beautiful", 3),
        # Trailing silent "e" is dropped before counting vowel groups...
        ("make", 1),
        ("queue", 1),
        # ...but a word must never score zero syllables.
        ("e", 1),
        ("rhythm", 1),
        ("the", 1),
        ("", 1),
        ("123", 1),
    ],
)
def test_count_syllables(word, expected):
    assert parsing.count_syllables(word) == expected
