import type { MetadataRoute } from "next";
const BASE = process.env.NEXT_PUBLIC_SITE_URL || "https://marketer.sh";
const ROUTES = [
  "",
  "/about",
  "/contact",
  "/demo",
  "/docs",
  "/features",
  "/features/ads",
  "/features/analytics",
  "/features/articles",
  "/features/automation",
  "/features/campaigns",
  "/features/content",
  "/features/dramas",
  "/features/library",
  "/features/motion",
  "/features/niches",
  "/features/scheduling",
  "/features/seo",
  "/features/seo-audit",
  "/features/templates",
  "/features/ugc",
  "/features/video",
  "/how-it-works",
  "/legal",
  "/legal/acceptable-use",
  "/legal/cookies",
  "/legal/dpa",
  "/legal/privacy",
  "/legal/refund",
  "/legal/subprocessors",
  "/legal/terms",
  "/pricing",
  "/resources",
  "/resources/api",
  "/resources/changelog",
  "/resources/faq",
  "/resources/guides",
  "/resources/guides/agent-driven-marketing",
  "/resources/guides/content-brief",
  "/resources/guides/first-channel",
  "/resources/guides/plan-content-budget",
  "/resources/guides/review-checklist",
  "/resources/guides/seo-articles",
  "/resources/help",
  "/resources/quickstart",
  "/use-cases",
  "/use-cases/agencies",
  "/use-cases/ai-agents",
  "/use-cases/creators",
  "/use-cases/ecommerce",
  "/use-cases/local-business",
  "/use-cases/saas",
];
export default function sitemap(): MetadataRoute.Sitemap {
  return ROUTES.map((path) => ({
    url: `${BASE}${path}`,
    changeFrequency: path === "" ? "weekly" : "monthly",
    priority: path === "" ? 1 : path.split("/").length <= 2 ? 0.8 : 0.6,
  }));
}
