import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
const p = await ctx.newPage();
await p.goto("http://localhost:3400/", { waitUntil: "networkidle" });
await p.waitForTimeout(2000);
await p.screenshot({ path: process.env.SC + "/shots/mobile-topcrop.png", clip: { x: 0, y: 60, width: 390, height: 220 } });
const ctx2 = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p2 = await ctx2.newPage();
await p2.goto("http://localhost:3400/", { waitUntil: "networkidle" });
await p2.waitForTimeout(2000);
await p2.screenshot({ path: process.env.SC + "/shots/desktop-handcrop.png", clip: { x: 600, y: 500, width: 600, height: 400 } });
await b.close();
